/**
 * Smoke contract for the post-revoke confirmation message format
 * (`/qurl send` → click Revoke → bot edits the ephemeral confirmation).
 *
 * The wording is generated by `renderRevokeMsg` in
 * apps/discord/src/commands.js. These assertions pin the user-facing
 * strings so an accidental rewording lands as a deploy-gate failure
 * instead of silent UX drift.
 *
 * Coverage gap acknowledged: this is fixture-based — it doesn't drive
 * the bot end-to-end (would require a real Discord user session). The
 * unit tests in apps/discord/tests/qurl-send-back-half.test.js exercise
 * `renderRevokeMsg` directly; this file's role is to fail the
 * post-deploy smoke when the contract regresses.
 */

// Mirrors `renderRevokeMsg`'s output regex shape. Keep in sync when
// changing the user-visible wording on the bot side.
const REVOKE_PREFIX_RE = /^Revoked \d+\/\d+ links?\./;
const REVOKE_FOR_LINE_RE = /^Revoked for: /m;
const SHOW_MORE_TRUNC_RE = /\+\d+ more$/m;

describe('qURL send revoke confirmation format (smoke)', () => {
  test('full-list format: "Revoked X/Y links" + "Revoked for: alice, bob"', () => {
    const msg = 'Revoked 3/3 links. Note: already-opened links cannot be revoked.\nRevoked for: alice, bob, carol';
    expect(REVOKE_PREFIX_RE.test(msg)).toBe(true);
    expect(REVOKE_FOR_LINE_RE.test(msg)).toBe(true);
    expect(SHOW_MORE_TRUNC_RE.test(msg)).toBe(false);
  });

  test('truncated format: "+N more" when names list exceeds TRUNC_LIMIT (5)', () => {
    const msg = 'Revoked 8/8 links. Note: already-opened links cannot be revoked.\nRevoked for: a, b, c, d, e +3 more';
    expect(REVOKE_PREFIX_RE.test(msg)).toBe(true);
    expect(SHOW_MORE_TRUNC_RE.test(msg)).toBe(true);
  });

  test('no-success format: "Revoked 0/N" omits "Revoked for:" line', () => {
    const msg = 'Revoked 0/5 links. Note: already-opened links cannot be revoked.';
    expect(msg).toMatch(/^Revoked 0\/5 links\./);
    expect(REVOKE_FOR_LINE_RE.test(msg)).toBe(false);
  });

  test('zero-attempt format: "Revoked 0/0" omits the already-opened note', () => {
    const msg = 'Revoked 0/0 links.';
    expect(msg).not.toContain('already-opened');
  });

  test('singular "link" when total === 1', () => {
    const msg = 'Revoked 1/1 link. Note: already-opened links cannot be revoked.\nRevoked for: alice';
    expect(msg).toMatch(/^Revoked 1\/1 link\./);
    expect(msg).not.toMatch(/^Revoked 1\/1 links\./);
  });
});
