package internal

import (
	"context"
	"encoding/json"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"

	"github.com/layervai/qurl-integrations/apps/slack/internal/agent"
)

func TestAgentFeedbackBlockContract(t *testing.T) {
	raw, err := json.Marshal(agentFeedbackBlock())
	if err != nil {
		t.Fatalf("marshal feedback block: %v", err)
	}
	got := string(raw)
	for _, want := range []string{
		`"type":"context_actions"`,
		`"type":"feedback_buttons"`,
		`"action_id":"` + agentFeedbackActionID + `"`,
		`"value":"` + agentFeedbackPositiveValue + `"`,
		`"value":"` + agentFeedbackNegativeValue + `"`,
		"Mark this qURL response as helpful",
		"Mark this qURL response as not helpful",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("feedback block missing %q: %s", want, got)
		}
	}
}

func TestDeliverAgentResultGeneratedReplyIncludesFeedbackWhenWired(t *testing.T) {
	textPost, posts, mu := capturingPostMessage()
	blocks := &blocksRecorder{}
	h := NewHandler(Config{
		PostMessage:       textPost,
		PostMessageBlocks: blocks.fn(),
		PostFeedback:      func(context.Context, []byte) error { return nil },
	})
	t.Cleanup(h.Wait)

	env := env(slackEventTypeAppMention, slackChannelTypeChannel, "U2", "", "", "")
	h.deliverAgentResult(slog.Default(), env, "100.1", &agent.Result{Reply: "Use **bold**."})

	mu.Lock()
	defer mu.Unlock()
	if len(*posts) != 0 {
		t.Fatalf("feedback-enabled generated reply must use blocks, got text posts %+v", *posts)
	}
	if len(blocks.calls) != 1 {
		t.Fatalf("blocks calls = %d, want 1", len(blocks.calls))
	}
	raw, _ := json.Marshal(blocks.calls[0].blocks)
	got := string(raw)
	for _, want := range []string{`"type":"markdown"`, "Use **bold**.", "Generated by AI (Anthropic Claude)", agentFeedbackActionID} {
		if !strings.Contains(got, want) {
			t.Errorf("generated reply blocks missing %q: %s", want, got)
		}
	}
}

func TestPostAgentGeneratedReplyFallsBackWhenFeedbackBlocksFail(t *testing.T) {
	textPost, posts, mu := capturingPostMessage()
	h := NewHandler(Config{
		PostMessage: textPost,
		PostMessageBlocks: func(context.Context, string, string, string, string, []any, string) error {
			return context.DeadlineExceeded
		},
		PostFeedback: func(context.Context, []byte) error { return nil },
	})
	env := env(slackEventTypeAppMention, slackChannelTypeChannel, "U2", "", "", "")
	h.postAgentGeneratedReply(slog.Default(), env, "100.1", "complete answer", textPost)

	mu.Lock()
	defer mu.Unlock()
	if len(*posts) != 1 || (*posts)[0].text != "complete answer" {
		t.Fatalf("fallback posts = %+v, want complete answer", *posts)
	}
}

func TestAgentStreamerGeneratedReplyStopsWithFeedback(t *testing.T) {
	port := &recordingStreamPort{}
	s := newTestStreamer(port)
	s.feedbackEnabled = true
	const reply = "You can reach staging from this channel."
	for _, chunk := range chunkStr(reply, 8) {
		s.onDelta(chunk)
	}
	if !s.finalizeReply(&agent.Result{Reply: reply}) {
		t.Fatal("streamed reply should be delivered")
	}
	raw, _ := json.Marshal(port.stopBlocks)
	if got := string(raw); !strings.Contains(got, agentFeedbackActionID) {
		t.Fatalf("stop blocks = %s, want feedback action", got)
	}
}

func TestHandleAgentFeedbackClickRoutesFixedRating(t *testing.T) {
	var posted []byte
	var response map[string]any
	responseServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if err := json.NewDecoder(r.Body).Decode(&response); err != nil {
			t.Errorf("decode response_url body: %v", err)
		}
		w.WriteHeader(http.StatusOK)
	}))
	t.Cleanup(responseServer.Close)
	h := NewHandler(Config{PostFeedback: func(_ context.Context, payload []byte) error {
		posted = append([]byte(nil), payload...)
		return nil
	}})
	h.validateResponseURLFn = func(string) (*url.URL, error) { return url.Parse(responseServer.URL) }

	payload := &interactionPayload{
		Type:        interactionTypeBlockActions,
		Team:        interactionID{ID: "T1"},
		User:        interactionID{ID: "U2"},
		Channel:     interactionID{ID: "C1"},
		Container:   interactionContainer{MessageTS: "1700.01"},
		ResponseURL: testSlackResponseURL,
		Actions: []interactionAction{{
			ActionID: agentFeedbackActionID,
			Value:    agentFeedbackNegativeValue,
		}},
	}
	w := httptest.NewRecorder()
	h.handleBlockActions(w, payload)
	h.Wait()

	if w.Code != 200 {
		t.Fatalf("ack code = %d, want 200", w.Code)
	}
	got := string(posted)
	for _, want := range []string{"Secure Access Agent response needs improvement", "Agent message `1700.01` in channel `C1`.", "user_id `U2`", "team_id `T1`"} {
		if !strings.Contains(got, want) {
			t.Errorf("feedback payload missing %q: %s", want, got)
		}
	}
	if text, _ := response[respFieldText].(string); !strings.Contains(text, "Thanks") {
		t.Fatalf("response_url body = %+v, want acknowledgement", response)
	}
}

func TestHandleAgentFeedbackClickRejectsUnknownRating(t *testing.T) {
	var calls int
	h := NewHandler(Config{PostFeedback: func(context.Context, []byte) error {
		calls++
		return nil
	}})
	payload := &interactionPayload{
		Team:    interactionID{ID: "T1"},
		Actions: []interactionAction{{ActionID: agentFeedbackActionID, Value: "unknown"}},
	}
	w := httptest.NewRecorder()
	h.handleBlockActions(w, payload)
	h.Wait()
	if w.Code != 200 || calls != 0 {
		t.Fatalf("ack=%d feedback calls=%d, want 200/0", w.Code, calls)
	}
}
