package internal

import (
	"context"
	"encoding/json"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"

	"github.com/layervai/qurl-integrations/apps/slack/internal/agent"
)

func TestAgentFeedbackBlockContract(t *testing.T) {
	raw, err := json.Marshal(agentFeedbackBlock())
	if err != nil {
		t.Fatalf("marshal feedback block: %v", err)
	}
	got := string(raw)
	for _, want := range []string{
		`"type":"context_actions"`,
		`"type":"feedback_buttons"`,
		`"action_id":"` + agentFeedbackActionID + `"`,
		`"value":"` + agentFeedbackPositiveValue + `"`,
		`"value":"` + agentFeedbackNegativeValue + `"`,
		"Mark this qURL response as helpful",
		"Mark this qURL response as not helpful",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("feedback block missing %q: %s", want, got)
		}
	}
}

func TestDeliverAgentResultGeneratedReplyIncludesFeedbackWhenWired(t *testing.T) {
	textPost, posts, mu := capturingPostMessage()
	blocks := &blocksRecorder{}
	h := NewHandler(Config{
		PostMessage:       textPost,
		PostMessageBlocks: blocks.fn(),
		PostFeedback:      func(context.Context, []byte) error { return nil },
		OpenView:          func(context.Context, string, string, []byte) error { return nil },
	})
	t.Cleanup(h.Wait)

	env := env(slackEventTypeAppMention, slackChannelTypeChannel, "U2", "", "", "")
	const reply = "Use **bold** and <https://example.com|this label>, not <raw markup>."
	h.deliverAgentResult(slog.Default(), env, "100.1", &agent.Result{Reply: reply})

	mu.Lock()
	defer mu.Unlock()
	if len(*posts) != 0 {
		t.Fatalf("feedback-enabled generated reply must use blocks, got text posts %+v", *posts)
	}
	if len(blocks.calls) != 1 {
		t.Fatalf("blocks calls = %d, want 1", len(blocks.calls))
	}
	raw, _ := json.Marshal(blocks.calls[0].blocks)
	got := string(raw)
	for _, want := range []string{`"type":"markdown"`, "Use **bold**", "Generated by AI (Anthropic Claude)", agentFeedbackActionID} {
		if !strings.Contains(got, want) {
			t.Errorf("generated reply blocks missing %q: %s", want, got)
		}
	}
	markdownBlock := blocks.calls[0].blocks[0].(map[string]any)
	if got, want := markdownBlock["text"], agentLLMReplyWithDisclaimer(hardenAgentMarkdown(reply)); got != want {
		t.Fatalf("markdown block text = %q, want exactly one hardening pass %q", got, want)
	}
}

func TestDeliverAgentProposalPreviewIncludesFeedbackWithoutReencoding(t *testing.T) {
	textPost, posts, mu := capturingPostMessage()
	blocks := &blocksRecorder{}
	h := NewHandler(Config{
		PostMessage:       textPost,
		PostMessageBlocks: blocks.fn(),
		PostFeedback:      func(context.Context, []byte) error { return nil },
		OpenView:          func(context.Context, string, string, []byte) error { return nil },
	})
	t.Cleanup(h.Wait)

	env := env(slackEventTypeAppMention, slackChannelTypeChannel, "U2", "", "", "")
	result := &agent.Result{Proposal: &agent.Proposal{Summary: "Expose <private> **now**"}}
	h.deliverAgentResult(slog.Default(), env, "100.1", result)

	mu.Lock()
	defer mu.Unlock()
	if len(*posts) != 0 || len(blocks.calls) != 1 {
		t.Fatalf("text posts=%d block calls=%d, want 0/1", len(*posts), len(blocks.calls))
	}
	markdownBlock := blocks.calls[0].blocks[0].(map[string]any)
	if got, want := markdownBlock["text"], agentReplyText(result); got != want {
		t.Fatalf("proposal preview text = %q, want existing escaped preview %q", got, want)
	}
}

func TestPostAgentGeneratedReplyFallsBackWhenFeedbackBlocksFail(t *testing.T) {
	textPost, posts, mu := capturingPostMessage()
	h := NewHandler(Config{
		PostMessage: textPost,
		PostMessageBlocks: func(context.Context, string, string, string, string, []any, string) error {
			return context.DeadlineExceeded
		},
		PostFeedback: func(context.Context, []byte) error { return nil },
		OpenView:     func(context.Context, string, string, []byte) error { return nil },
	})
	env := env(slackEventTypeAppMention, slackChannelTypeChannel, "U2", "", "", "")
	h.postAgentGeneratedReply(slog.Default(), env, "100.1", "complete answer", textPost)

	mu.Lock()
	defer mu.Unlock()
	if len(*posts) != 1 || (*posts)[0].text != "complete answer" {
		t.Fatalf("fallback posts = %+v, want complete answer", *posts)
	}
}

func TestAgentStreamerGeneratedReplyStopsWithFeedback(t *testing.T) {
	port := &recordingStreamPort{}
	s := newTestStreamer(port)
	s.feedbackEnabled = true
	const reply = "You can reach staging from this channel."
	for _, chunk := range chunkStr(reply, 8) {
		s.onDelta(chunk)
	}
	if !s.finalizeReply(&agent.Result{Reply: reply}) {
		t.Fatal("streamed reply should be delivered")
	}
	raw, _ := json.Marshal(port.stopBlocks)
	if got := string(raw); !strings.Contains(got, agentFeedbackActionID) {
		t.Fatalf("stop blocks = %s, want feedback action", got)
	}
}

func TestHandleAgentHelpfulFeedbackOnlyAcknowledges(t *testing.T) {
	var feedbackCalls, openViewCalls int
	var response map[string]any
	responseServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if err := json.NewDecoder(r.Body).Decode(&response); err != nil {
			t.Errorf("decode response_url body: %v", err)
		}
		w.WriteHeader(http.StatusOK)
	}))
	t.Cleanup(responseServer.Close)
	h := NewHandler(Config{
		PostFeedback: func(context.Context, []byte) error {
			feedbackCalls++
			return nil
		},
		OpenView: func(context.Context, string, string, []byte) error {
			openViewCalls++
			return nil
		},
	})
	h.validateResponseURLFn = func(string) (*url.URL, error) { return url.Parse(responseServer.URL) }

	payload := &interactionPayload{
		Type:        interactionTypeBlockActions,
		Team:        interactionID{ID: "T1"},
		User:        interactionID{ID: "U2"},
		Channel:     interactionID{ID: "C1"},
		ResponseURL: testSlackResponseURL,
		Actions: []interactionAction{{
			ActionID: agentFeedbackActionID,
			Value:    agentFeedbackPositiveValue,
		}},
	}
	w := httptest.NewRecorder()
	h.handleBlockActions(w, payload)
	h.Wait()

	if w.Code != 200 {
		t.Fatalf("ack code = %d, want 200", w.Code)
	}
	if feedbackCalls != 0 || openViewCalls != 0 {
		t.Fatalf("feedback calls=%d open view calls=%d, want 0/0", feedbackCalls, openViewCalls)
	}
	if text, _ := response[respFieldText].(string); !strings.Contains(text, "Thanks") {
		t.Fatalf("response_url body = %+v, want acknowledgement", response)
	}
}

func TestHandleAgentNotHelpfulFeedbackOpensExistingModal(t *testing.T) {
	var feedbackCalls int
	var gotTeamID, gotTriggerID string
	var gotView []byte
	h := NewHandler(Config{
		PostFeedback: func(context.Context, []byte) error {
			feedbackCalls++
			return nil
		},
		OpenView: func(_ context.Context, teamID, triggerID string, view []byte) error {
			gotTeamID = teamID
			gotTriggerID = triggerID
			gotView = append([]byte(nil), view...)
			return nil
		},
	})
	payload := &interactionPayload{
		Type:        interactionTypeBlockActions,
		Team:        interactionID{ID: "T1"},
		Enterprise:  interactionID{ID: "E1"},
		User:        interactionID{ID: "U2"},
		TriggerID:   "trigger-feedback",
		Channel:     interactionID{ID: "C1"},
		ResponseURL: testSlackResponseURL,
		Actions: []interactionAction{{
			ActionID: agentFeedbackActionID,
			Value:    agentFeedbackNegativeValue,
		}},
	}
	w := httptest.NewRecorder()
	h.handleBlockActions(w, payload)
	h.Wait()

	if w.Code != http.StatusOK {
		t.Fatalf("ack code = %d, want 200", w.Code)
	}
	if feedbackCalls != 0 {
		t.Fatalf("feedback webhook calls = %d, want 0 before modal submission", feedbackCalls)
	}
	if gotTeamID != "T1" || gotTriggerID != "trigger-feedback" {
		t.Fatalf("views.open team=%q trigger=%q, want T1/trigger-feedback", gotTeamID, gotTriggerID)
	}
	var view struct {
		CallbackID      string `json:"callback_id"`
		PrivateMetadata string `json:"private_metadata"`
	}
	if err := json.Unmarshal(gotView, &view); err != nil {
		t.Fatalf("decode feedback modal: %v", err)
	}
	if view.CallbackID != callbackIDFeedback {
		t.Fatalf("callback_id = %q, want existing feedback callback %q", view.CallbackID, callbackIDFeedback)
	}
	var meta FeedbackModalMetadata
	if err := json.Unmarshal([]byte(view.PrivateMetadata), &meta); err != nil {
		t.Fatalf("decode feedback metadata: %v", err)
	}
	if meta.TeamID != "T1" || meta.UserID != "U2" || meta.ChannelID != "C1" || meta.EnterpriseID != "E1" || meta.ResponseURL != testSlackResponseURL {
		t.Fatalf("feedback metadata = %+v, want clicked response context", meta)
	}
}

func TestAgentFeedbackControlsRequireFeedbackModal(t *testing.T) {
	textPost, posts, mu := capturingPostMessage()
	blocks := &blocksRecorder{}
	h := NewHandler(Config{
		PostMessage:       textPost,
		PostMessageBlocks: blocks.fn(),
		PostFeedback:      func(context.Context, []byte) error { return nil },
	})
	env := env(slackEventTypeAppMention, slackChannelTypeChannel, "U2", "", "", "")
	h.deliverAgentResult(slog.Default(), env, "100.1", &agent.Result{Reply: "complete answer"})

	mu.Lock()
	defer mu.Unlock()
	if len(*posts) != 1 || len(blocks.calls) != 0 {
		t.Fatalf("text posts=%d block calls=%d, want 1/0 without OpenView", len(*posts), len(blocks.calls))
	}
}

func TestHandleAgentFeedbackClickRejectsUnknownRating(t *testing.T) {
	var calls int
	h := NewHandler(Config{PostFeedback: func(context.Context, []byte) error {
		calls++
		return nil
	}})
	payload := &interactionPayload{
		Team:    interactionID{ID: "T1"},
		Actions: []interactionAction{{ActionID: agentFeedbackActionID, Value: "unknown"}},
	}
	w := httptest.NewRecorder()
	h.handleBlockActions(w, payload)
	h.Wait()
	if w.Code != 200 || calls != 0 {
		t.Fatalf("ack=%d feedback calls=%d, want 200/0", w.Code, calls)
	}
}
