package internal

import (
	"context"
	"encoding/json"
	"errors"
	"log/slog"
	"reflect"
	"regexp"
	"runtime/debug"
	"strings"
	"time"

	"github.com/layervai/qurl-integrations/apps/slack/internal/agent"
	"github.com/layervai/qurl-integrations/apps/slack/internal/slackdata"
)

// Slack Events API event types this handler reacts to.
const (
	slackEventTypeAppMention                    = "app_mention"
	slackEventTypeMessage                       = "message"
	slackEventTypeAssistantThreadStarted        = "assistant_thread_started"
	slackEventTypeAssistantThreadContextChanged = "assistant_thread_context_changed"
	slackEventTypeAppHomeOpened                 = "app_home_opened"
	slackChannelTypeChannel                     = "channel"
	slackChannelTypeGroup                       = "group"
	slackChannelTypeIM                          = "im"
	slackChannelTypeMPIM                        = "mpim"
	slackMessageSubtypeThreadBroadcast          = "thread_broadcast"
)

// agentProposalPreviewPrefix prefixes a proposed-mutation reply while
// conversation mode is read-only (the confirm flow lands in a follow-up). The
// agent only ever proposes; it never executes, so a preview is the honest reply.
const agentProposalPreviewPrefix = "I can set that up, but applying changes from conversation mode isn't enabled yet. Here's what I'd do once it is:\n• "

// agentErrorReply is posted when a turn fails unexpectedly. Deliberately vague —
// internals never reach the channel.
const agentErrorReply = "Something went wrong handling that. Please try again, or use a `/qurl` command."

// agentAIPrivacyURL is the privacy notice for the Secure Access Agent's AI
// features. Surfaced in every AI-disclosure string below so users always have a
// route to how their messages are processed.
const agentAIPrivacyURL = "https://layerv.ai/privacy/"

// agentAIDisclosure is the Slack-Marketplace-required AI disclosure for the
// agent surface: it names the AI provider (Anthropic Claude), warns that AI can
// be wrong (review before approving), notes the paid-plan requirement for Slack
// AI apps, and links the privacy notice. Used as the pane's first-run intro and
// kept as one const so the App Home / pane copy can't drift on the load-bearing
// points (AI used + can be wrong + privacy link).
const agentAIDisclosure = "I use AI (Anthropic Claude) to interpret requests and can make mistakes — review any proposed action before approving. AI features require a paid Slack plan. Privacy: " + agentAIPrivacyURL

// agentAIDisclosureShort is the App Home context-block variant of
// agentAIDisclosure — the same load-bearing points (AI used + can be wrong +
// privacy link) in the tighter form a context block wants.
const agentAIDisclosureShort = "🤖 Uses AI (Anthropic Claude) and can make mistakes — review actions before approving. Privacy: " + agentAIPrivacyURL

// agentConfirmAIDisclosure is the small AI-provenance line on the proposed-action
// confirm card, reminding the approver the proposal came from the AI agent before
// they approve it.
const agentConfirmAIDisclosure = "🤖 Proposed by the AI agent — review before approving."

// agentLLMReplyDisclaimer is appended only to ordinary free-text model replies.
// Fixed errors, deterministic help, proposal previews, and confirmation cards have
// their own provenance/copy and must not be mislabeled as AI-generated. Keep this
// string invariant under the one-shot and stream-reconcile Markdown hardeners; the
// streaming path appends the trusted constant directly.
const agentLLMReplyDisclaimer = "\n\n_Generated by AI (Anthropic Claude). It may contain mistakes; review before acting._"

func agentLLMReplyWithDisclaimer(markdown string) string {
	return markdown + agentLLMReplyDisclaimer
}

// agentTransientReply is posted when a turn fails for a likely-transient reason —
// the turn-budget deadline elapsed, or the context was canceled — as opposed to
// agentErrorReply's generic failure. Slack's agent-design guidance is to separate
// "temporarily unavailable, worth retrying" from a capability limit so the user
// knows a retry is worthwhile; a done turn ctx is our reliable signal for the
// former. Still leaks no internals.
const agentTransientReply = "That took longer than I could handle just now — please try again, or use a `/qurl` command."

// agentRateLimitedReply is posted when a turn is dropped for hitting the per-user or
// per-team turn-rate cap. Deliberately uniform across both limits (don't leak which
// cap, or its value) and points at the always-available slash commands. Phrased
// neutrally ("conversation mode is at its limit", not "you've reached…") so it
// doesn't wrongly blame an innocent member when it's the per-workspace cap that hit.
const agentRateLimitedReply = "Conversation mode is at its limit for now — give it a few minutes, or use a `/qurl` command in the meantime."

// agentTurnRateWindow is the fixed window for the per-user / per-team turn counters.
// The env limits are expressed per hour, so the window is one hour.
const agentTurnRateWindow = time.Hour

// agentTurnRateCounterFailOpenMsg is an infra-observed contract: the CloudWatch
// metric filter added in qurl-integrations-infra#1065 keys on this exact slog
// msg value for the fail-open path introduced by qurl-integrations-infra#1055.
// TODO(upstream-contract): keep this value in lockstep with that infra filter.
const agentTurnRateCounterFailOpenMsg = "agent: turn-rate counter failed; allowing turn (fail-open)"

// agentAckReaction is the glanceable "working on it" emoji the agent adds to the
// triggering message while a turn runs (reactions.add), then removes when it ends.
const agentAckReaction = "eyes"

// defaultAgentAckTimeout bounds each cosmetic working-on-it round-trip. Channel
// turns use async reactions.add plus deferred reactions.remove; exclusive pane
// mode uses assistant-pane setStatus; default pre-pane mode still attempts both
// the reaction fallback and setStatus for im turns. It's deliberately tight and
// decoupled from the 4s chat.postMessage budget: a "working on it" ack that
// hasn't landed in ~2s is already too late to feel responsive, so giving up (no
// 👀 — the deferred remove then hits no_reaction → benign) beats delaying the
// turn it's meant to make feel responsive.
// On a very fast turn with a still-running add, deferred clear can spend one budget
// joining the add before spending a fresh budget on remove; both happen after reply
// delivery, so the user-visible turn stays unblocked, but the agent worker slot stays
// occupied until the deferred clear returns. In that slow-reaction/fast-reply case,
// the reaction may briefly appear after the reply before clear removes it; preserving
// add-before-remove ordering is the no-stale-reaction priority.
const defaultAgentAckTimeout = 2 * time.Second

// agentThinkingStatus is the native assistant-pane status text shown while a DM (pane)
// turn runs (assistant.threads.setStatus); Slack renders it as "<app> is thinking…".
// See setAgentThinkingStatus.
const agentThinkingStatus = "is thinking…"

// slackEventEnvelope is the Events API outer payload. Only the fields the agent
// surface needs are modeled.
type slackEventEnvelope struct {
	Type           string                    `json:"type"`
	Challenge      string                    `json:"challenge"`
	TeamID         string                    `json:"team_id"`
	EnterpriseID   string                    `json:"enterprise_id"`
	APIAppID       string                    `json:"api_app_id"`
	EventID        string                    `json:"event_id"`
	EventTime      int64                     `json:"event_time,omitempty"`
	Authorizations []slackEventAuthorization `json:"authorizations,omitempty"`
	Event          slackInnerEvent           `json:"event"`
}

type slackEventAuthorization struct {
	EnterpriseID        string `json:"enterprise_id,omitempty"`
	TeamID              string `json:"team_id,omitempty"`
	IsEnterpriseInstall bool   `json:"is_enterprise_install,omitempty"`
}

// slackInnerEvent is the inner `event` object for app_mention / message events,
// plus the assistant_thread object on the container events (assistant_thread_started
// and assistant_thread_context_changed).
type slackInnerEvent struct {
	Type        string `json:"type"`
	User        string `json:"user"`
	UserTeam    string `json:"user_team,omitempty"`
	SourceTeam  string `json:"source_team,omitempty"`
	BotID       string `json:"bot_id"`
	Subtype     string `json:"subtype"`
	Text        string `json:"text"`
	Channel     string `json:"channel"`
	ChannelType string `json:"channel_type"`
	TS          string `json:"ts"`
	ThreadTS    string `json:"thread_ts"`
	// Tab is the App Home tab a user opened ("home" / "messages") on an
	// app_home_opened event; empty on every other event type.
	Tab string `json:"tab,omitempty"`
	// AssistantThread is set on the container events (assistant_thread_started and
	// assistant_thread_context_changed), which carry a nested object, not the flat fields.
	AssistantThread *assistantThread    `json:"assistant_thread,omitempty"`
	Tokens          *slackRevokedTokens `json:"tokens,omitempty"`
}

type slackRevokedTokens struct {
	Bot   []string `json:"bot,omitempty"`
	OAuth []string `json:"oauth,omitempty"`
}

// assistantThread is the assistant_thread object on a container event: the assistant DM
// channel + thread the user opened, plus the context (the channel they were viewing).
// Context.ChannelID is persisted by the container handlers for a later turn to scope its
// reads to.
type assistantThread struct {
	UserID    string                 `json:"user_id"`
	ChannelID string                 `json:"channel_id"`
	ThreadTS  string                 `json:"thread_ts"`
	Context   assistantThreadContext `json:"context"`
}

type assistantThreadContext struct {
	ChannelID    string `json:"channel_id"`
	TeamID       string `json:"team_id"`
	EnterpriseID string `json:"enterprise_id"`
}

// agentEnabled reports whether conversation mode is fully wired and not killed.
func (h *Handler) agentEnabled() bool {
	return !h.cfg.AgentDisabled &&
		h.cfg.AgentLLM != nil &&
		h.cfg.AgentStore != nil &&
		h.cfg.PostMessage != nil
}

// agentChannelFollowupsEnabled reports whether the agent answers non-@mention thread
// replies in channel threads it already joined (see shouldDispatchAgentEvent). Gated
// on top of agentEnabled and dark by default: turning it on means subscribing to
// message.channels/groups (channels:history/groups:history), so the bot then RECEIVES
// every message in channels it's a member of — a data-handling expansion that must be
// reviewed and re-OAuth'd before enabling. Until then channels stay @mention-per-turn.
func (h *Handler) agentChannelFollowupsEnabled() bool {
	return h.agentEnabled() && h.cfg.AgentChannelFollowups
}

// workspaceAgentEnabled resolves the per-workspace conversation-mode toggle, on top
// of the org-level agentEnabled gate: the stored agent_enabled flag if the workspace
// set it (AgentEnabledFor), else Config.AgentDefaultEnabled. It FAILS CLOSED on a
// read error — don't run the agent if we can't confirm the workspace opted in, and
// never override an explicit opt-out on a transient blip. With no AdminStore wired
// there's no per-workspace store to read, so the org default governs. The read is a
// single workspace_mappings GetItem, off the ack path (callers are already async).
func (h *Handler) workspaceAgentEnabled(ctx context.Context, log *slog.Logger, teamID string) bool {
	if h.cfg.AdminStore == nil {
		return h.cfg.AgentDefaultEnabled
	}
	enabled, set, err := h.cfg.AdminStore.AgentEnabledFor(ctx, teamID)
	if err != nil {
		log.Warn("agent: per-workspace toggle read failed; treating as disabled", "team_id", teamID, "error", err)
		return false
	}
	if set {
		return enabled
	}
	return h.cfg.AgentDefaultEnabled
}

// agentTurnLimited enforces the per-user and per-team turn-rate caps for one turn,
// returning the reply to post when the turn must be dropped. It is a COST BACKSTOP,
// not a security gate, so it FAILS OPEN: a transient counter error logs and allows
// the turn rather than dropping a legitimate member — the opposite of the
// fail-closed workspace/dedupe gates. The per-user counter is bumped FIRST so one
// member spamming can't inflate the shared per-team counter for everyone else.
//
// One asymmetry, by design: a turn the per-user cap denies never reaches the
// per-team counter, but a turn the per-team cap denies has ALREADY incremented the
// per-user counter (it was a real attempt). Both only inflate within the window and
// reset when it rolls, so it's a non-issue for a backstop.
func (h *Handler) agentTurnLimited(ctx context.Context, log *slog.Logger, env *slackEventEnvelope) (reply string, limited bool) {
	// A non-positive limit disables that scope (unlimited), so each guard also
	// short-circuits the counter bump when its cap is off — both off ⇒ no DDB calls.
	// env.Event.User is non-empty here: shouldDispatchAgentEvent (the only gate before
	// processAgentEvent) rejects e.User == "", so the per-user scope can't collapse
	// into one shared "user#" bucket.
	if l := h.cfg.AgentMaxTurnsPerUserPerHour; l > 0 && h.overTurnLimit(ctx, log, env.TeamID, "user#"+env.Event.User, l) {
		return agentRateLimitedReply, true
	}
	if l := h.cfg.AgentMaxTurnsPerTeamPerHour; l > 0 && h.overTurnLimit(ctx, log, env.TeamID, "team", l) {
		return agentRateLimitedReply, true
	}
	return "", false
}

// overTurnLimit bumps the named fixed-window counter and reports whether this turn
// crossed the limit. Fails OPEN (returns false) on a counter error — a conscious
// tradeoff: this leaves the cap weakest exactly under DDB stress (throttling is also
// when a busy workspace racks up cost), but dropping a legitimate member's turn on a
// transient blip is worse for a backstop than briefly running uncapped.
func (h *Handler) overTurnLimit(ctx context.Context, log *slog.Logger, teamID, scope string, limit int) bool {
	count, err := h.cfg.AgentStore.BumpTurnCount(ctx, teamID, scope, agentTurnRateWindow)
	if err != nil {
		log.Warn(agentTurnRateCounterFailOpenMsg, "scope", scope, "team_id", teamID, "error", err)
		return false
	}
	if count > int64(limit) {
		log.Info("agent: turn rate limit reached", "scope", scope, "team_id", teamID, "count", count, "limit", limit)
		return true
	}
	return false
}

func (h *Handler) effectiveAgentAckTimeout() time.Duration {
	if h.agentAckTimeout > 0 {
		return h.agentAckTimeout
	}
	// NewHandler normalizes this for production. This fallback, like the nil-base
	// fallback in agentAckContext, only protects package-local bare Handler literals in
	// focused unit tests that call ack helpers directly.
	return defaultAgentAckTimeout
}

func (h *Handler) agentAckContext() (context.Context, context.CancelFunc) {
	baseCtx := h.baseCtx
	if baseCtx == nil {
		// NewHandler normalizes this for production; this is the matching bare-test-literal
		// fallback for direct ack-helper tests.
		baseCtx = context.Background()
	}
	return context.WithTimeout(baseCtx, h.effectiveAgentAckTimeout())
}

type agentAckAdd struct {
	done   <-chan struct{}
	cancel context.CancelFunc
}

// addAgentAck reacts agentAckReaction (👀) on the triggering message to acknowledge
// the turn is being worked. Best-effort: a failed ack never fails the turn, and a nil
// Reactions seam is a no-op (the ack is simply absent). The add runs asynchronously so
// Slack reaction latency stays off the LLM turn's critical path. The returned handle
// is load-bearing: clearAgentAck waits for it before removing so reactions.remove can
// never race ahead of an in-flight reactions.add and strand the 👀.
func (h *Handler) addAgentAck(log *slog.Logger, env *slackEventEnvelope) agentAckAdd {
	if h.cfg.Reactions == nil {
		return agentAckAdd{}
	}
	done := make(chan struct{})
	ctx, cancel := h.agentAckContext()
	// Nested Add is safe because the caller is processAgentEvent, already running
	// inside runOnPool's wg slot; the counter cannot hit zero between this Add and
	// the goroutine start.
	// The goroutine is wg-tracked, so shutdown drain relies on ReactionPort.Add
	// honoring ctx just like the other Slack seams wired through Handler.
	h.asyncStart()
	go func() {
		defer h.asyncDone()
		defer close(done)
		defer func() {
			if rec := recover(); rec != nil {
				log.Error("panic in agent ack add", "recover", rec, "stack", string(debug.Stack()))
			}
		}()

		defer cancel()
		if err := h.cfg.Reactions.Add(ctx, env.TeamID, env.EnterpriseID, env.Event.Channel, env.Event.TS, agentAckReaction); err != nil {
			if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
				log.Debug("agent: ack reaction add canceled or timed out (best-effort)", "error", err)
				return
			}
			log.Warn("agent: ack reaction add failed (best-effort)", "error", err)
		}
	}()
	return agentAckAdd{done: done, cancel: cancel}
}

// clearAgentAck removes the working-on-it reaction when the turn ends — deferred so it
// runs on EVERY exit (reply posted, error, panic). Best-effort and nil-safe like
// addAgentAck. It waits on the add handle before removing so even a very fast turn cannot
// remove before the async add lands. The wait is bounded too: if a future seam ignores
// its add context, or the add goroutine starts late enough that the join budget wins,
// clear abandons the best-effort remove rather than recreating the remove-before-add
// race. On abandon, clear also cancels the in-flight add context: if the ReactionPort
// honors ctx, no late 👀 lands; if it ignores ctx, the operator-facing Warn still says
// the ack may remain. The remove uses a FRESH ctx off baseCtx: by defer time the turn
// ctx is spent (agentTurnTimeout elapsed, or shutdown), so removing on it would fail
// instantly and strand the 👀 — the same spent-ctx lesson as postAgentReply. It gets
// a full fresh ack budget rather than the leftover join budget so a slow add that
// finally settled does not starve the cleanup call.
func (h *Handler) clearAgentAck(log *slog.Logger, env *slackEventEnvelope, add agentAckAdd) {
	if h.cfg.Reactions == nil || add.done == nil {
		return
	}
	// Non-blocking peek first: on a turn where the async add already landed, skip the
	// joinCtx allocation entirely (and avoid the deterministic-shutdown nuance below
	// where add.done and joinCtx.Done() can be ready simultaneously after a successful
	// add -- Go's select would pick uniformly at random and spuriously log).
	select {
	case <-add.done:
	default:
		joinCtx, joinCancel := h.agentAckContext()
		defer joinCancel()
		select {
		case <-add.done:
		case <-joinCtx.Done():
			if add.cancel != nil {
				add.cancel()
			}
			if h.baseCtx != nil && h.baseCtx.Err() != nil {
				log.Debug("agent: ack reaction add unfinished during shutdown; skipping remove")
			} else {
				log.Warn("agent: ack reaction add still in flight; skipping remove to avoid racing add; ack may remain")
			}
			return
		}
	}

	ctx, cancel := h.agentAckContext()
	defer cancel()
	if err := h.cfg.Reactions.Remove(ctx, env.TeamID, env.EnterpriseID, env.Event.Channel, env.Event.TS, agentAckReaction); err != nil {
		if h.baseCtx != nil && h.baseCtx.Err() != nil && (errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded)) {
			log.Debug("agent: ack reaction remove canceled during shutdown; ack may remain", "error", err)
			return
		}
		log.Warn("agent: ack reaction remove failed (best-effort)", "error", err)
	}
}

// setAgentThinkingStatus shows the native assistant "thinking…" status in the pane for a
// DM (message.im) turn — the pane-native counterpart to addAgentAck's 👀 reaction.
// Best-effort behind the AssistantThreads seam (nil = no-op) and ONLY for im turns:
// app_mention is a channel, not an assistant thread, so setStatus has nothing to scope
// to. Set SYNCHRONOUSLY on the live turn ctx before the LLM call so it's visible while
// the turn runs, under its own agentAckTimeout cap. The old #693 additive pre-LLM
// concern no longer stacks with reaction add (now async); setStatus remains the one
// synchronous working-on-it seam here. There is NO deferred clear: Slack auto-clears
// the status when the agent posts its reply (every turn exit posts one), and a
// 2-minute server-side timeout backstops the no-reply case. The auto-clear only fires
// when the reply lands on the SAME thread the status was set on, so the thread_ts here
// MUST equal the reply's — both derive from agentEventRootTS(&env.Event); keep them
// coupled.
//
// Post-enablement exclusive mode treats a pane setStatus failure as evidence the
// native status path is broken (scope, rate limit, malformed thread, etc.), so it logs
// at Warn while keeping the turn best-effort. Pre-enable additive mode still logs at
// Debug because setStatus may fail on every ordinary DM until the pane is live and the
// reaction remains the working cue.
func (h *Handler) setAgentThinkingStatus(ctx context.Context, log *slog.Logger, env *slackEventEnvelope) {
	if h.cfg.AssistantThreads == nil || env.Event.ChannelType != slackChannelTypeIM {
		return
	}
	ctx, cancel := context.WithTimeout(ctx, h.effectiveAgentAckTimeout())
	defer cancel()
	if err := h.cfg.AssistantThreads.SetStatus(ctx, env.TeamID, env.EnterpriseID, env.Event.Channel, agentEventRootTS(&env.Event), agentThinkingStatus); err != nil {
		if !h.cfg.AgentSurfaceExclusiveAcks {
			log.Debug("agent: set assistant pane status failed (best-effort)", "error", err)
			return
		}
		log.Warn("agent: set assistant pane status failed in exclusive mode", "error", err)
		return
	}
}

// startAgentReactionAck marks an admitted turn with the reaction indicator when
// this surface still uses one. The add is best-effort; cleanup is also
// nil-/no-reaction-safe.
func (h *Handler) startAgentReactionAck(log *slog.Logger, env *slackEventEnvelope) agentAckAdd {
	if env.Event.ChannelType == slackChannelTypeIM && h.cfg.AgentSurfaceExclusiveAcks {
		return agentAckAdd{}
	}
	return h.addAgentAck(log, env)
}

// agentOperatingChannel is the channel the agent OPERATES on for this turn (scopes
// every channel-scoped read via TurnContext.ChannelID). For an @mention it's the
// channel the mention came from; for an assistant-pane (DM) turn it's the channel the
// user opened the pane FROM — but only when they're a confirmed member of it
// (paneContextChannel), else the bare DM. The reply still posts to env.Event.Channel;
// only the operating channel changes. The mutation path is unaffected — it anchors to
// env.Event.Channel / the click's channel, never this — so the override widens reads
// only, never actions.
func (h *Handler) agentOperatingChannel(ctx context.Context, log *slog.Logger, env *slackEventEnvelope) string {
	if env.Event.ChannelType == slackChannelTypeIM {
		if c := h.paneContextChannel(ctx, log, env); c != "" {
			return c
		}
	}
	return env.Event.Channel
}

// handleAgentEvent decides whether an event_callback should drive a
// conversation turn and, if so, dispatches it to the async pool. The caller
// (handleEvent) always acks 200 regardless — Slack must not retry — so this only
// schedules work; it never writes the response.
func (h *Handler) handleAgentEvent(env *slackEventEnvelope) {
	if !h.agentEnabled() {
		return
	}
	// Assistants-container events are additive (no conversation turn) — handle them
	// before the turn-dispatch filter, which only admits app_mention/message. Both carry
	// the pane's context.channel_id (the channel the user opened it from); the started
	// event also sets the first-run title + prompts.
	switch env.Event.Type {
	case slackEventTypeAssistantThreadStarted:
		h.handleAssistantThreadStarted(env)
		return
	case slackEventTypeAssistantThreadContextChanged:
		h.handleAssistantThreadContextChanged(env)
		return
	case slackEventTypeAppHomeOpened:
		// App Home tab opened — publish the viewer's own agent-action review surface.
		// Additive (no conversation turn), like the container events above.
		h.handleAppHomeOpened(env)
		return
	}
	if !shouldDispatchAgentEvent(env, h.agentChannelFollowupsEnabled()) {
		return
	}
	log := slog.With(
		"surface", "agent",
		"team_id", env.TeamID,
		"enterprise_id", env.EnterpriseID,
		"channel_id", env.Event.Channel,
		"event_id", env.EventID,
	)
	envCopy := *env
	turn := func(ctx context.Context, log *slog.Logger) {
		h.processAgentEvent(ctx, log, &envCopy)
	}
	// Channel thread follow-ups first pass through a short SEPARATE gate pool before
	// admitted turns move to h.followupSem. That keeps a message.channels firehose from
	// spending long-running turn slots on "is this our thread?" DDB reads, while both
	// stages stay isolated from the main pool that @mention/DM/slash/interaction work
	// shares (#712/#719).
	if isAgentChannelFollowup(&envCopy.Event) {
		if !h.runAgentFollowupPipeline(log, &envCopy) {
			log.Warn("agent: follow-up gate pool saturated — dropping channel reply")
		}
		return
	}
	// Main pool, via runOnPool directly (not startAsyncWorkerWithTimeout) so this path
	// logs its drop exactly once — symmetric with the follow-up branch above. (The
	// startAsyncWorkerWithTimeout wrapper keeps its own saturation log for runAsync/slash
	// callers, which have no caller-side log.)
	if !h.runOnPool(h.sem, log, agentTurnTimeout, turn) {
		log.Warn("agent: async pool saturated — dropping event")
	}
}

// runAgentFollowupPipeline runs the channel-follow-up admission gate and, only when the
// thread is one the agent already joined, the full follow-up turn. It is intentionally a
// single wg-tracked goroutine: wg.Add happens on the request goroutine before spawn, while
// the short gate semaphore is released before the long follow-up turn starts.
func (h *Handler) runAgentFollowupPipeline(log *slog.Logger, env *slackEventEnvelope) bool {
	select {
	case h.followupGateSem <- struct{}{}:
	default:
		return false
	}

	h.asyncStart()
	go func() {
		gateHeld := true
		defer h.asyncDone()
		defer func() {
			if gateHeld {
				<-h.followupGateSem
			}
		}()
		defer func() {
			if rec := recover(); rec != nil {
				log.Error("panic in agent follow-up pipeline", "recover", rec, "stack", string(debug.Stack()))
			}
		}()

		partition := agentEventPartition(env)
		admitted, pre := func() (bool, *loadedHistory) {
			gateCtx, cancelGate := context.WithTimeout(h.baseCtx, agentFollowupGateTimeout)
			defer cancelGate()
			return h.admitAgentChannelFollowup(gateCtx, log, env, partition)
		}()

		<-h.followupGateSem
		gateHeld = false
		if !admitted {
			return
		}

		select {
		case h.followupSem <- struct{}{}:
		default:
			log.Warn("agent: follow-up turn pool saturated — dropping admitted channel reply")
			return
		}
		defer func() { <-h.followupSem }()

		turnCtx, cancelTurn := context.WithTimeout(h.baseCtx, agentTurnTimeout)
		defer cancelTurn()
		h.processAdmittedAgentEvent(turnCtx, log, env, partition, pre)
	}()
	return true
}

// agentTurnTimeout bounds one conversation turn. A turn makes up to
// defaultMaxIterations Anthropic round-trips plus channel-scoped reads, so it
// needs more than the 25s slash-command budget — 25s could cancel a legitimate
// multi-tool-call turn mid-flight and surface a spurious error to the user. The
// iteration cap and (later) per-user rate limiting bound how long a slot is held.
const agentTurnTimeout = 90 * time.Second

// agentFollowupGateTimeout bounds the pre-turn DDB reads for a channel follow-up
// admission decision. A slow gate fails closed silently because the message may be
// unrelated channel chatter; admitted turns get the larger agentTurnTimeout budget.
const agentFollowupGateTimeout = 5 * time.Second

// agentDeliveryBudget bounds each post-turn delivery step — the transcript save
// and the reply post each derive their own context with this budget off
// h.baseCtx, never the turn ctx. By delivery time the turn ctx may be spent or
// canceled (the turn hit agentTurnTimeout), and a SaveConversation / PostMessage
// on a dead ctx fails instantly — yet the dedupe write is already committed and
// Slack won't retry, so the user would get silence. Deriving off baseCtx (like
// callerIsAdmin) lets delivery outlive the turn deadline; bounding it (not
// baseCtx directly) keeps a wedged Slack/DDB call from pinning an async-pool slot
// and lets SIGTERM still drain in-flight delivery.
const agentDeliveryBudget = 15 * time.Second

// shouldDispatchAgentEvent filters out everything that isn't a human asking the
// agent something: non-mention/DM events, bot and system/edited messages (the
// self-loop guard), authorless events, top-level channel messages, and empty text.
//
// When channelFollowupsEnabled is true, a channel message that is a thread REPLY is
// also admitted — so a follow-up in a thread the agent is already in continues the
// conversation without a re-@mention. Slack's thread_broadcast subtype follows that
// same path when a user also sends the thread reply to the channel.
// runAgentFollowupPipeline then confirms it's the agent's OWN thread (it has saved
// history) before answering; a top-level channel message is never admitted, so we never
// respond to un-addressed channel chatter.
func shouldDispatchAgentEvent(env *slackEventEnvelope, channelFollowupsEnabled bool) bool {
	e := &env.Event
	// Drop bot posts and the agent's own messages before considering event shape.
	if e.BotID != "" || e.User == "" {
		return false
	}
	switch e.Type {
	case slackEventTypeAppMention:
		// Channel @-mention — always a deliberate address.
		if e.Subtype != "" {
			return false
		}
	case slackEventTypeMessage:
		if e.ChannelType == slackChannelTypeIM {
			// DMs are deliberate only when they are ordinary human messages. A subtyped
			// DM remains system/bot/edit-like noise from this surface's perspective.
			if e.Subtype != "" {
				return false
			}
		} else {
			if e.Subtype != "" && e.Subtype != slackMessageSubtypeThreadBroadcast {
				return false
			}
			// A channel message reaches the follow-up pipeline only when channel
			// follow-ups are enabled AND it's a thread reply. The pipeline then checks
			// whether this is already an agent thread, using store access.
			if !channelFollowupsEnabled || e.ThreadTS == "" {
				return false
			}
		}
	default:
		return false
	}
	return strings.TrimSpace(stripBotMention(e.Text)) != ""
}

// isAgentChannelFollowup reports whether this event is a non-@mention reply in a
// channel thread (vs an app_mention or a DM). When shouldDispatchAgentEvent admits a
// channel message it is, by construction, a thread reply — so the follow-up pipeline
// uses this to apply the extra "must be the agent's own thread" gate that DMs and
// @mentions skip.
func isAgentChannelFollowup(e *slackInnerEvent) bool {
	return e.Type == slackEventTypeMessage && e.ChannelType != slackChannelTypeIM && e.ThreadTS != ""
}

// loadedHistory carries a thread's transcript plus its store version from the channel-
// follow-up gate to the turn, so the accepted-follow-up path reads DynamoDB once (the
// gate's read is reused as the turn's load) instead of twice. A nil *loadedHistory means
// "not preloaded" — the @mention/DM path skips the gate and loads at the turn. Reusing the
// gate's read snapshots version slightly earlier (before dedupe/ack), so the read→save
// window is marginally wider on this path; a concurrent save is then no worse than a
// version conflict, which saveAgentHistory already resolves by reload-and-merge.
type loadedHistory struct {
	history []agent.Message
	version int64
}

// admitAgentChannelFollowup performs the short pre-turn checks for a channel follow-up:
// workspace toggle plus "is this already an agent thread?" transcript lookup. Accepted
// replies carry the loaded transcript forward so the turn does not repeat the read.
func (h *Handler) admitAgentChannelFollowup(ctx context.Context, log *slog.Logger, env *slackEventEnvelope, partition string) (admitted bool, pre *loadedHistory) {
	// Per-workspace toggle stays before the transcript gate so a disabled workspace
	// consumes no dedupe marker and performs no agent turn. This gate runs off the
	// request path, so the extra read does not threaten Slack's ack deadline.
	if !h.workspaceAgentEnabled(ctx, log, env.TeamID) {
		log.Info("agent: conversation mode disabled for this workspace; ignoring channel follow-up")
		return false, nil
	}
	dropped, pre := h.agentChannelFollowupDropped(ctx, log, env, partition)
	return !dropped, pre
}

// agentChannelFollowupDropped reports whether this event is a channel thread reply
// the agent should NOT answer: a reply with no readable transcript for the thread — one
// it never joined, or joined but whose blob is empty or undecodable (loadAgentHistory
// reports a corrupt blob as no history, deliberately, so it also fail-closed-drops here),
// or one whose lookup errored. It returns dropped=false for non-follow-ups — @mentions
// and DMs are always deliberate addresses. Called before dedupe/ack so a reply that isn't
// ours consumes no dedupe marker and gets no 👀, and (when the lookup fails) we stay
// SILENT rather than posting an error into what may be unrelated channel chatter. On an
// ADMITTED follow-up it returns the loaded transcript so the turn reuses it instead of
// re-reading — one DynamoDB read per accepted follow-up, not two. The firehose admission
// load this read sits on is isolated to the short gate pool in runAgentFollowupPipeline.
func (h *Handler) agentChannelFollowupDropped(ctx context.Context, log *slog.Logger, env *slackEventEnvelope, partition string) (dropped bool, pre *loadedHistory) {
	if !isAgentChannelFollowup(&env.Event) {
		return false, nil
	}
	history, version, err := h.loadAgentHistory(ctx, log, partition, agentEventThreadKey(env))
	if err != nil {
		log.Error("agent: thread-continuity lookup failed; dropping channel reply", "error", err)
		return true, nil
	}
	if len(history) == 0 {
		log.Debug("agent: channel reply outside an agent thread; ignoring")
		return true, nil
	}
	return false, &loadedHistory{history: history, version: version}
}

// resolveTurnHistory returns the transcript for this turn: the follow-up gate's preloaded
// read on an accepted follow-up (pre != nil — one DynamoDB read, not two), else a fresh
// load for the @mention/DM path. On a load error it posts the generic reply — the dedupe
// marker is already committed, so Slack won't retry and we own the reply rather than
// leaving the @-mention silently unanswered (already logged in loadAgentHistory) — and
// returns ok=false so the caller stops.
func (h *Handler) resolveTurnHistory(ctx context.Context, log *slog.Logger, env *slackEventEnvelope, partition, threadKey string, pre *loadedHistory) (history []agent.Message, version int64, ok bool) {
	if pre != nil {
		return pre.history, pre.version, true
	}
	history, version, err := h.loadAgentHistory(ctx, log, partition, threadKey)
	if err != nil {
		h.postAgentReply(log, env, agentEventRootTS(&env.Event), agentErrorReply)
		return nil, 0, false
	}
	return history, version, true
}

// botMentionPattern matches a leading Slack user mention, e.g. "<@U123>" or
// "<@U123|name>", so an @-mention's text can be reduced to the actual request.
// The [UW][A-Z0-9]{8,63} id body matches the established mention-id grammar in
// parser.go's userMentionPattern (rejects toy ids; caps pathological pastes) —
// this one strips a leading mention rather than validating a whole token, so the
// anchoring differs, but the id charset is kept in sync.
var botMentionPattern = regexp.MustCompile(`^\s*<@[UW][A-Z0-9]{8,63}(?:\|[^>]*)?>\s*`)

// stripBotMention removes a leading bot mention from app_mention text.
func stripBotMention(text string) string {
	return strings.TrimSpace(botMentionPattern.ReplaceAllString(text, ""))
}

// agentEventPartition is the conversation/dedupe partition key. It deliberately
// uses the same resolver as lifecycleWorkspaceIDs: org-level installs write those
// rows under enterprise_id, workspace-level installs write under team_id, and the
// lifecycle purge also sweeps any team-keyed agent-state partitions Slack
// includes on org callbacks for pending actions, audit, pane context, and rate
// counters.
func agentEventPartition(env *slackEventEnvelope) string {
	return resolveSlackEventPartitions(env).agentWrite
}

// agentEventRootTS is the thread root a turn belongs to: the parent thread_ts
// when the message is already in a thread, else the message's own ts (which the
// reply threads under).
func agentEventRootTS(e *slackInnerEvent) string {
	if e.ThreadTS != "" {
		return e.ThreadTS
	}
	return e.TS
}

// agentThreadKey identifies one thread — channel + thread root — and is the single
// format for both the conversation-history key and (for an assistant pane) the stored
// context key. The container events persist context under agentThreadKey(at.ChannelID,
// at.ThreadTS); a pane turn reads it under agentEventThreadKey(env), which delegates
// here — so the two can't drift out of alignment.
func agentThreadKey(channelID, threadRootTS string) string {
	return channelID + ":" + threadRootTS
}

// agentEventThreadKey identifies one conversation: channel + thread root.
func agentEventThreadKey(env *slackEventEnvelope) string {
	return agentThreadKey(env.Event.Channel, agentEventRootTS(&env.Event))
}

// agentEventDedupeKey identifies the inbound MESSAGE — channel + the message's
// OWN ts — so every delivery of one message (a retry, or overlapping app_mention
// + message.im events with distinct event_ids) shares it and dedupes to one turn.
// It is deliberately env.Event.TS, NOT agentEventRootTS: a follow-up in a thread
// shares the thread root but has its own ts, so keying on the root would make the
// dedupe drop every threaded follow-up. Distinct from agentEventThreadKey for
// exactly that reason.
func agentEventDedupeKey(env *slackEventEnvelope) string {
	return env.Event.Channel + ":" + env.Event.TS
}

// processAgentEvent runs one deliberate @mention/DM conversation turn on the async
// pool: workspace gate, dedupe, load history, run the agent, persist, and post the reply.
func (h *Handler) processAgentEvent(ctx context.Context, log *slog.Logger, env *slackEventEnvelope) {
	h.processAgentEventWithAdmission(ctx, log, env, "", nil, false)
}

// processAdmittedAgentEvent runs a channel follow-up after runAgentFollowupPipeline has
// already checked the workspace toggle and loaded the thread transcript under the short
// admission gate.
func (h *Handler) processAdmittedAgentEvent(ctx context.Context, log *slog.Logger, env *slackEventEnvelope, partition string, pre *loadedHistory) {
	h.processAgentEventWithAdmission(ctx, log, env, partition, pre, true)
}

func (h *Handler) processAgentEventWithAdmission(ctx context.Context, log *slog.Logger, env *slackEventEnvelope, admittedPartition string, pre *loadedHistory, preadmitted bool) {
	// Panic safety-net: we've already acked 200 and may have committed the dedupe
	// marker, so Slack won't retry. If the turn panics, startAsyncWorker's recover
	// would log+swallow but post nothing, leaving the @-mention silently
	// unanswered. Absorb the panic here instead — log the stack (the worker recover
	// won't see it) and post the generic reply on a fresh ctx (postAgentReply
	// self-derives one) so the user always hears something went wrong.
	defer func() {
		if rec := recover(); rec != nil {
			log.Error("agent: panic during turn", "recover", rec, "stack", string(debug.Stack()))
			h.postAgentReply(log, env, agentEventRootTS(&env.Event), agentErrorReply)
		}
	}()

	partition, pre, ok := h.prepareAgentEventAdmission(ctx, log, env, admittedPartition, pre, preadmitted)
	if !ok {
		return
	}

	// Dedupe on message identity (see agentEventDedupeKey), not the per-delivery
	// event_id: two events for one message would otherwise both win and double-reply.
	first, err := h.cfg.AgentStore.MarkEventSeen(ctx, partition, agentEventDedupeKey(env))
	if err != nil {
		// Fail closed: dropping a turn on a transient error beats a double reply.
		log.Error("agent: dedupe check failed; dropping event", "error", err)
		return
	}
	if !first {
		log.Info("agent: duplicate event ignored")
		return
	}

	// Rate-limit AFTER dedupe (count unique messages, not redeliveries) and BEFORE
	// the turn runs (the LLM is the cost we're capping). Confirm-clicks
	// (processAgentConfirm) are deliberately NOT limited: they're consume-once and
	// admin-gated and carry no LLM cost. A limited turn still gets a reply — silence
	// would read as the agent ignoring the member.
	//
	// The count is of turn ATTEMPTS, not answered turns — a turn bumped here that then
	// fails transiently (agentTransientReply) still counts, so the cap is "N
	// attempts/hour". That's the right unit for a COST backstop: the LLM round-trip is
	// the spend whether or not it produced a usable answer.
	if reply, limited := h.agentTurnLimited(ctx, log, env); limited {
		h.postAgentReply(log, env, agentEventRootTS(&env.Event), reply)
		return
	}

	// Working-on-it ack: before the pane rollout flag flips, pane turns keep the
	// reaction fallback plus best-effort native status; after it flips, pane turns use
	// only Slack's native assistant status. Channel turns always use the eyes reaction.
	// Register reaction cleanup before attempting native status so a status-path panic
	// cannot strand the fallback reaction. The add runs async, but clear joins its
	// completion handle before removing so the remove can't race ahead.
	add := h.startAgentReactionAck(log, env)
	defer h.clearAgentAck(log, env, add)
	h.setAgentThinkingStatus(ctx, log, env)

	threadKey := agentEventThreadKey(env)
	history, version, ok := h.resolveTurnHistory(ctx, log, env, partition, threadKey, pre)
	if !ok {
		return
	}

	operatingChannel := h.agentOperatingChannel(ctx, log, env)

	// Resolve the operating channel's name for a friendlier system prompt ("#general (C123)"
	// vs the bare id). A 1:1 DM with no pane context has no usable name → skipped; a scoped
	// pane operates on a real channel, so it resolves like an @mention. (An app_mention in a
	// group DM still resolves but yields no name → negative-cached, harmless.) Cached per
	// channel (channelNameTTL), best-effort; describeChannel falls back to the id when empty.
	channelName := ""
	if operatingChannel != env.Event.Channel || env.Event.ChannelType != slackChannelTypeIM {
		channelName = h.resolveChannelName(ctx, log, env.TeamID, env.EnterpriseID, operatingChannel)
	}
	tc := agent.TurnContext{
		TeamID:        env.TeamID,
		EnterpriseID:  env.EnterpriseID,
		ChannelID:     operatingChannel,
		ChannelName:   channelName,
		UserID:        env.Event.User,
		CallerIsAdmin: h.callerIsAdmin(log, env.TeamID, env.Event.User),
	}

	replyTS := agentEventRootTS(&env.Event)
	// Native reply streaming: when the AgentStream seam is wired and the event is a
	// pane DM or channel @mention, the reply renders token-by-token instead of as one
	// posted message. nil otherwise — the agent keeps the normal post path. Per-turn
	// (a fresh streamer/Run).
	streamer := h.newAgentReplyStreamer(ctx, log, env, replyTS)
	var streamOpts []agent.Option
	if streamer != nil {
		streamOpts = append(streamOpts, agent.WithStreamSink(streamer.onDelta))
	}
	a := agent.New(h.cfg.AgentLLM, h.newAgentBackend(log), streamOpts...)
	result, newHistory, err := a.Run(ctx, &tc, history, stripBotMention(env.Event.Text))

	if err != nil {
		log.Error("agent: turn failed", "error", err)
		// A HEALTHY live stream owns the (partial) outcome — deltas already delivered aren't
		// rolled back — so finalize the partial rather than double-posting an error over it.
		// finalizeError returns false (→ post the error below) when no stream opened, or when the
		// stream BROKE mid-flight and left a truncated partial the user shouldn't read as final.
		if streamer == nil || !streamer.finalizeError() {
			reply := agentErrorReply
			if ctx.Err() != nil {
				// The turn ctx is done (agentTurnTimeout elapsed, or baseCtx canceled on
				// shutdown): a transient timeout, not a capability limit — invite a retry.
				reply = agentTransientReply
			}
			h.postAgentReply(log, env, replyTS, reply)
		}
		return
	}

	// Token usage per turn (summed across the agent's round-trips). The cache
	// counters are the operator hook for confirming whether prompt caching is
	// paying off once conversation mode is live (see the agent package).
	log.Info("agent: turn complete",
		"proposed", result.Proposal != nil,
		"input_tokens", result.Usage.InputTokens,
		"output_tokens", result.Usage.OutputTokens,
		"cache_read_tokens", result.Usage.CacheReadInputTokens,
		"cache_creation_tokens", result.Usage.CacheCreationInputTokens,
	)

	// Save before posting: the transcript must be durably consistent before the
	// user can fire a follow-up turn against it. The post is the slower,
	// user-visible step, so this trades a little reply latency for that ordering.
	//
	// a.Run returns the loaded `history` as an exact prefix of newHistory (it
	// copies history, then appends this turn's messages — pinned by
	// agent.TestRun_AppendsToPriorHistoryWithoutMutatingInput). So this turn's
	// delta is the suffix; saveAgentHistory re-applies just it onto the winner's
	// transcript if a concurrent turn won the save race. Verify that invariant at
	// runtime (not just len(newHistory) >= len(history)): if a.Run ever stops being
	// pure-append, leave delta nil so a conflict DROPS this turn rather than
	// grafting a wrong suffix onto the winner — the silent corruption #666 exists to
	// prevent. The first save still persists newHistory normally; only the
	// conflict-merge is skipped.
	var delta []agent.Message
	if agentRunPreservedPrefix(history, newHistory) {
		delta = newHistory[len(history):]
	} else {
		log.Error("agent: a.Run did not return loaded history as an exact prefix; conflict-merge disabled for this turn")
	}
	h.saveAgentHistory(log, partition, threadKey, newHistory, delta, version)

	// A live stream delivers the reply itself (finalizeReply flushes + stops it), so the
	// caller skips the post — the no-double-post invariant. It returns false when no stream
	// opened (no deltas), when the stream broke mid-flight (the caller posts the full reply
	// over the truncated partial), or for a proposal, whose streamed text was only the agent's
	// narration; the confirm card is still delivered below as a separate message.
	if streamer != nil && streamer.finalizeReply(&result) {
		return
	}
	// Deliver: an interactive confirm card for an executable proposal once the
	// confirm flow is enabled, else the text reply/preview (merged #650 behavior).
	h.deliverAgentResult(log, env, replyTS, &result)
}

// loadAgentHistory reads and decodes a thread's transcript. A decode error is
// treated as an empty thread (start fresh) rather than a hard failure; the
// loaded version is preserved either way so the next SaveConversation still
// passes the optimistic-concurrency check (and a corrupt blob gets overwritten).
func (h *Handler) loadAgentHistory(ctx context.Context, log *slog.Logger, partition, threadKey string) ([]agent.Message, int64, error) {
	blob, version, err := h.cfg.AgentStore.LoadConversation(ctx, partition, threadKey)
	if err != nil {
		log.Error("agent: load conversation failed", "error", err)
		return nil, 0, err
	}
	if len(blob) == 0 {
		return nil, version, nil
	}
	var history []agent.Message
	if err := json.Unmarshal(blob, &history); err != nil {
		log.Warn("agent: corrupt conversation history; starting fresh", "error", err)
		return nil, version, nil
	}
	return history, version, nil
}

// maxPersistedMessages bounds the transcript persisted per thread so a long
// thread can't grow the DynamoDB item toward the 400KB limit (at which point the
// save fails and the thread loses continuity). At ~2 messages per plain Q&A turn
// and ~4 per tool-using turn, 40 messages is roughly the last 10–20 turns —
// ample given the per-turn work cap; older turns are trimmed.
const maxPersistedMessages = 40

// maxPersistedBytes caps the serialized transcript well under DynamoDB's 400KB
// item limit. The message-count cap alone doesn't bound bytes — a single large
// tool_result could still bloat the item — so we also drop oldest turns until
// the blob fits. (Read-only tool output is compact today; this matters more once
// mutation tool_results land.)
const maxPersistedBytes = 350 * 1024

// agentRunPreservedPrefix reports whether newHistory begins with loaded
// element-for-element — the exact-prefix invariant a.Run guarantees (it copies
// loaded, then appends this turn's messages) and that the conflict-merge delta
// (newHistory[len(loaded):]) depends on. The call site verifies this at runtime,
// not just len(newHistory) >= len(loaded): a future a.Run that rewrote or
// reordered earlier turns while netting longer (e.g. history compaction) would
// pass a length check yet make the suffix a WRONG delta — grafting it onto a
// concurrent winner's transcript is the silent corruption #666 prevents. Cheap:
// runs once per turn (post-LLM), at most maxPersistedMessages comparisons.
func agentRunPreservedPrefix(loaded, newHistory []agent.Message) bool {
	if len(newHistory) < len(loaded) {
		return false
	}
	for i := range loaded {
		if !reflect.DeepEqual(loaded[i], newHistory[i]) {
			return false
		}
	}
	return true
}

// saveAgentHistory persists the updated transcript under optimistic concurrency,
// trimmed to a bounded length and byte size. If a concurrent turn on the same
// thread won the version race (ErrConversationConflict), it reloads the winner's
// transcript, re-applies just this turn's delta on top, and retries exactly once,
// so a parallel turn no longer silently drops this turn's reply from the thread.
//
// delta is this turn's appended suffix (the messages a.Run added on top of the
// transcript loaded at turn start — computed at the call site). It always begins
// with the user message a.Run prepends, the same clean boundary as any cross-turn
// append, so grafting it onto the winner's (turn-end) transcript is well-formed by
// the same construction that makes sequential turns well-formed. The grafted reply
// was computed against the pre-conflict context, so it may be slightly stale
// relative to the winner's turn — structurally valid, semantically best-effort,
// and strictly better than dropping the turn.
//
// Persistence runs on its own context off h.baseCtx (see agentDeliveryBudget), not
// the possibly-spent turn ctx. One reload+retry, not a loop: under sustained
// contention the user can re-ask; an unbounded race would pin the worker.
func (h *Handler) saveAgentHistory(log *slog.Logger, partition, threadKey string, updated, delta []agent.Message, version int64) {
	ctx, cancel := context.WithTimeout(h.baseCtx, agentDeliveryBudget)
	defer cancel()

	if err := h.persistBoundedHistory(ctx, log, partition, threadKey, updated, version); !errors.Is(err, slackdata.ErrConversationConflict) {
		return // saved, or a non-retryable failure already logged
	}
	// A concurrent turn advanced the stored version. Merge this turn's delta onto
	// the winner's transcript so neither turn is lost, then retry exactly once.
	if len(delta) == 0 {
		// Nothing to re-apply: the turn appended nothing on top of the base, or the
		// a.Run prefix invariant was violated (guarded at the call site). Drop,
		// matching pre-merge behavior.
		log.Info("agent: conversation version conflict; concurrent turn won, no delta to merge")
		return
	}
	if len(delta[0].ToolResults) > 0 {
		// Defense-in-depth for the merge seam: a.Run always begins this turn's delta
		// with the user message it prepends (a clean turn boundary), never a
		// tool_results message. If that ever stops holding (e.g. a.Run starts
		// compacting history), grafting a delta that opens with tool_results onto the
		// winner's transcript would leave an orphaned tool_result at the seam — drop
		// rather than persist a malformed transcript that would poison every future
		// turn on this thread. trimAgentHistory can't be relied on to repair this: a
		// short merged transcript is never trimmed.
		log.Warn("agent: conversation version conflict; delta head is a tool_results message, dropping turn")
		return
	}
	reloaded, reVersion, ok := h.reloadForMerge(ctx, log, partition, threadKey)
	if !ok {
		log.Info("agent: conversation version conflict; reload for merge failed, dropping turn")
		return
	}
	merged := make([]agent.Message, 0, len(reloaded)+len(delta))
	merged = append(merged, reloaded...)
	merged = append(merged, delta...)
	if err := h.persistBoundedHistory(ctx, log, partition, threadKey, merged, reVersion); errors.Is(err, slackdata.ErrConversationConflict) {
		log.Info("agent: conversation version conflict persisted again after one retry; dropping turn")
	}
}

func (h *Handler) prepareAgentEventAdmission(ctx context.Context, log *slog.Logger, env *slackEventEnvelope, partition string, pre *loadedHistory, preadmitted bool) (string, *loadedHistory, bool) {
	if partition == "" {
		partition = agentEventPartition(env)
	}
	if preadmitted {
		return partition, pre, true
	}

	// Per-workspace toggle, BEFORE the dedupe marker so a disabled workspace consumes
	// nothing. A workspace that hasn't opted in (or opted out) gets no reply — the
	// same silent behavior as the org-level dark surface; members use slash commands.
	if !h.workspaceAgentEnabled(ctx, log, env.TeamID) {
		log.Info("agent: conversation mode disabled for this workspace; ignoring @mention/DM")
		return partition, nil, false
	}

	// Channel thread-reply continuity gate — BEFORE dedupe/ack so a reply that isn't
	// ours consumes nothing and is never acked (see agentChannelFollowupDropped). On an
	// admitted follow-up it returns the loaded transcript so the turn below reuses it.
	dropped, loaded := h.agentChannelFollowupDropped(ctx, log, env, partition)
	if dropped {
		return partition, nil, false
	}
	return partition, loaded, true
}

// persistBoundedHistory trims history to the message-count and byte caps, marshals
// it, and writes it at expectedVersion under optimistic concurrency. It returns
// ErrConversationConflict (for the caller's retry decision) on a version clash; a
// marshal failure or a non-conflict save error is logged here and returns nil —
// nothing the caller can usefully retry.
func (h *Handler) persistBoundedHistory(ctx context.Context, log *slog.Logger, partition, threadKey string, history []agent.Message, expectedVersion int64) error {
	trimmed := trimAgentHistory(history, maxPersistedMessages)
	blob, err := json.Marshal(trimmed)
	if err != nil {
		log.Error("agent: marshal conversation failed", "error", err)
		return nil
	}
	// Byte guard: drop oldest turns (one per pass — trimAgentHistory cuts at a
	// turn boundary) until the blob fits or only the latest turn remains. Break
	// when a pass makes no progress: trimAgentHistory cuts only at a user-turn
	// start, so a single turn whose own tool_result blows past the cap has no
	// boundary below it and returns unchanged — without this guard the loop would
	// spin forever (a tight CPU loop no context can interrupt). In that case we
	// save oversized and let DDB reject + log rather than hang the worker.
	for len(blob) > maxPersistedBytes && len(trimmed) > 1 {
		next := trimAgentHistory(trimmed, len(trimmed)-1)
		if len(next) == len(trimmed) {
			break
		}
		trimmed = next
		if blob, err = json.Marshal(trimmed); err != nil {
			log.Error("agent: marshal conversation failed", "error", err)
			return nil
		}
	}
	switch err := h.cfg.AgentStore.SaveConversation(ctx, partition, threadKey, blob, expectedVersion); {
	case errors.Is(err, slackdata.ErrConversationConflict):
		return err
	case err != nil:
		log.Error("agent: save conversation failed", "error", err)
		return nil
	}
	return nil
}

// reloadForMerge re-reads a thread's transcript for the conflict-retry merge.
// Unlike loadAgentHistory (which treats a corrupt blob as an empty thread to be
// overwritten), a hard load error OR a decode failure here returns ok=false: the
// retry must not graft this turn's delta onto a garbage base, and overwriting the
// winner's blob with only this turn's delta would lose the winner's turn. Both
// cases drop, preserving whatever the winner stored. (The decode branch is nearly
// unreachable — the winner wrote that blob with the same marshal path — so the
// hard-load-error branch is the realistic one.)
func (h *Handler) reloadForMerge(ctx context.Context, log *slog.Logger, partition, threadKey string) ([]agent.Message, int64, bool) {
	blob, version, err := h.cfg.AgentStore.LoadConversation(ctx, partition, threadKey)
	if err != nil {
		log.Error("agent: reload conversation for merge failed", "error", err)
		return nil, 0, false
	}
	if len(blob) == 0 {
		return nil, version, true
	}
	var history []agent.Message
	if err := json.Unmarshal(blob, &history); err != nil {
		log.Warn("agent: reload conversation for merge: corrupt blob, dropping turn", "error", err)
		return nil, 0, false
	}
	return history, version, true
}

// trimAgentHistory bounds the transcript to roughly the most recent maxMessages,
// cutting only at the start of a user turn (a user message carrying text). That
// guarantees the kept slice never begins with an orphaned tool_result or an
// assistant tool_use whose result was trimmed away — both of which the model API
// rejects. If the trim window holds no clean boundary (an unusually long single
// turn), it falls back to the last turn start anywhere so the result is still
// bounded; only a transcript with no user-text turn at all is returned as-is.
func trimAgentHistory(msgs []agent.Message, maxMessages int) []agent.Message {
	if len(msgs) <= maxMessages {
		return msgs
	}
	for i := len(msgs) - maxMessages; i < len(msgs); i++ {
		if isUserTurnStart(&msgs[i]) {
			return msgs[i:]
		}
	}
	for i := len(msgs) - 1; i >= 0; i-- {
		if isUserTurnStart(&msgs[i]) {
			return msgs[i:]
		}
	}
	return msgs
}

// isUserTurnStart reports whether m begins a user turn — a user message with
// text, as opposed to a user message carrying tool_results. "user" is the agent
// package's wire role value.
func isUserTurnStart(m *agent.Message) bool {
	return m.Role == "user" && strings.TrimSpace(m.Text) != ""
}

// callerIsAdmin resolves the caller's admin status off the base context (a
// client abort can't cancel the fail-closed check). Missing store → not admin.
func (h *Handler) callerIsAdmin(log *slog.Logger, teamID, userID string) bool {
	if h.cfg.AdminStore == nil {
		return false
	}
	gateCtx, cancel := context.WithTimeout(h.baseCtx, adminGateBudget)
	defer cancel()
	isAdmin, _, err := h.cfg.AdminStore.CheckAdmin(gateCtx, teamID, userID)
	if err != nil {
		// Fail closed, but log for parity with the other CheckAdmin call sites
		// (requireAdminSync, the owner gate) so a systematic admin-check failure
		// — DDB throttling, a perms regression — is visible on the agent path
		// rather than silently denying admin features.
		log.Error("agent: admin check failed; treating caller as non-admin", "error", err, "team_id", teamID, "user_id", userID)
		return false
	}
	return isAdmin
}

// agentReplyText renders the mrkdwn text-seam reply for a turn: the escaped
// proposal preview while conversation mode is read-only, else the generic error
// reply. The agent's own free-text answer does NOT come through here — it posts as
// standard Markdown (see deliverAgentResult), which intercepts a non-blank answer
// before the fallback reaches this function. So a non-proposal result arriving here
// is the blank-answer case, and renders the error reply.
func agentReplyText(result *agent.Result) string {
	if result.Proposal == nil {
		return agentErrorReply
	}
	// A blank summary would render as a dangling "• " bullet; fall back to the error
	// reply rather than post an empty preview.
	if strings.TrimSpace(result.Proposal.Summary) == "" {
		return agentErrorReply
	}
	// The preview posts as mrkdwn, and the summary is LLM-distilled — escape it
	// (consistent with the confirm card's fallback) so a prompt-injected masked link
	// can't surface.
	return agentProposalPreviewPrefix + escapeMrkdwnText(result.Proposal.Summary)
}

// postAgentReply delivers a mrkdwn reply in-thread — the escaped proposal preview
// or a fixed error string. (The agent's free-text answer goes via
// postAgentMarkdownReply instead; see deliverAgentResult.)
func (h *Handler) postAgentReply(log *slog.Logger, env *slackEventEnvelope, threadTS, text string) {
	h.deliverAgentText(log, env, threadTS, text, h.cfg.PostMessage)
}

// postAgentMarkdownReply delivers the agent's free-text answer as standard
// Markdown rendered by Slack, with masked links already neutralized by the caller.
// When the markdown seam is unwired (PostMarkdownMessage nil) it falls back to the
// mrkdwn PostMessage seam: degraded rendering, and not a full defense for Slack's
// own <url|label> mrkdwn masking syntax, but still a delivered pre-enablement
// answer rather than a dropped one. The production seam wires PostMarkdownMessage.
func (h *Handler) postAgentMarkdownReply(log *slog.Logger, env *slackEventEnvelope, threadTS, markdown string) {
	post := h.cfg.PostMarkdownMessage
	if post == nil {
		post = h.cfg.PostMessage
	}
	h.deliverAgentText(log, env, threadTS, markdown, post)
}

// deliverAgentText posts text to the thread via the given seam. It derives its own
// context off h.baseCtx (see agentDeliveryBudget) rather than the turn ctx, so a
// turn that spent its deadline still delivers its reply. Failures are logged, not
// surfaced.
func (h *Handler) deliverAgentText(log *slog.Logger, env *slackEventEnvelope, threadTS, text string, post PostMessageFunc) {
	ctx, cancel := context.WithTimeout(h.baseCtx, agentDeliveryBudget)
	defer cancel()
	if err := post(ctx, env.TeamID, env.EnterpriseID, env.Event.Channel, threadTS, text); err != nil {
		log.Error("agent: post reply failed", "error", err)
	}
}
