package matchedcohort

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"sync"
	"time"

	qurl "github.com/layervai/qurl-go/qurl"

	"github.com/layervai/qurl-integrations/apps/cli/internal/connector/frpgen"
	"github.com/layervai/qurl-integrations/apps/cli/internal/connector/supervisor"
)

const lifecycleIntentSchema = 1

var lifecycleLabels = map[string][2]string{
	"direct": {labelDirectA, labelDirectB},
	"relay":  {labelRelayC, labelRelayD},
}

// LifecycleIntent is the immutable, offline, three-operation plan for one
// direct or relay customer journey. It is committed before any KNK. A runner
// restart reloads the same RunIDs and deadlines, so it can prepare or recover
// the exact operations without generating replacement authority.
type LifecycleIntent struct {
	Schema           int                        `json:"schema"`
	ReleaseID        string                     `json:"release_id"`
	Phase            string                     `json:"phase"`
	Attempt          uint64                     `json:"attempt"`
	Transport        string                     `json:"transport"`
	NHPSourceSHA     string                     `json:"nhp_source_sha"`
	AuthoritySHA256  string                     `json:"authority_sha256"`
	RecoveryEndpoint qurl.NHPUDPEndpoint        `json:"recovery_endpoint"`
	Operations       []LifecycleOperationIntent `json:"operations"`
}

// LifecycleOperationIntent binds one pre-network session attempt.
type LifecycleOperationIntent struct {
	Role         string `json:"role"`
	Label        string `json:"label"`
	RunID        string `json:"run_id"`
	RunAttempt   uint64 `json:"run_attempt"`
	PreparedAtMS int64  `json:"prepared_at_ms"`
	ExpiresAtMS  int64  `json:"expires_at_ms"`
}

// LifecycleIntentInput supplies all random and time authority before the
// immutable intent write. RunIDs must be generated by the orchestration
// process before this call; this package does not generate authority after a
// durable boundary.
type LifecycleIntentInput struct {
	ReleaseID        string
	Phase            string
	Attempt          uint64
	Transport        string
	RecoveryEndpoint qurl.NHPUDPEndpoint
	RunIDs           [3]string
	PreparedAt       time.Time
	ExpiresAt        time.Time
	AgentStates      map[string]StateReference
}

// PreparedLifecycle contains the three exact durable operation keys. All are
// PREPARED before this value is returned.
type PreparedLifecycle struct {
	IntentReference StateReference
	Intent          LifecycleIntent
	PrimaryFirstKey string
	SiblingKey      string
	ReplacementKey  string
}

// PrepareLifecycle commits the immutable three-operation intent and all
// operation records before any network-facing runner can start.
func (c *Consumer) PrepareLifecycle(ctx context.Context, authority Authority, input LifecycleIntentInput) (PreparedLifecycle, error) { //nolint:gocritic,gocyclo // One closed lifecycle authority is validated explicitly.
	if c == nil || c.Blobs == nil || ValidateAuthority(authority) != nil || !hex64Pattern.MatchString(input.ReleaseID) ||
		!validText(input.Phase) || input.Attempt == 0 {
		return PreparedLifecycle{}, fmt.Errorf("%w: lifecycle authority", errInvalidAuthority)
	}
	labels, ok := lifecycleLabels[input.Transport]
	if !ok || input.Phase != "fixed_shared_"+input.Transport || input.RecoveryEndpoint.Port != 443 || !validDNS(input.RecoveryEndpoint.Host) ||
		!validBase64Raw32(input.RecoveryEndpoint.ServerPublicKeyB64) {
		return PreparedLifecycle{}, fmt.Errorf("%w: lifecycle route or transport", errInvalidAuthority)
	}
	if input.AgentStates != nil && len(input.AgentStates) != 2 {
		return PreparedLifecycle{}, fmt.Errorf("%w: lifecycle refreshed state set", errInvalidAuthority)
	}
	for _, label := range labels {
		if input.AgentStates != nil && validateStateReference(input.AgentStates[label]) != nil {
			return PreparedLifecycle{}, fmt.Errorf("%w: lifecycle refreshed state", errInvalidAuthority)
		}
	}
	if input.PreparedAt.IsZero() || input.ExpiresAt.IsZero() || !input.ExpiresAt.After(input.PreparedAt) ||
		input.ExpiresAt.Sub(input.PreparedAt) > 30*time.Minute {
		return PreparedLifecycle{}, fmt.Errorf("%w: lifecycle operation time", errInvalidAuthority)
	}
	for _, runID := range input.RunIDs {
		if err := qurl.ValidateCycleRunID(runID); err != nil {
			return PreparedLifecycle{}, fmt.Errorf("%w: lifecycle RunID", errInvalidAuthority)
		}
	}
	if input.RunIDs[0] == input.RunIDs[1] || input.RunIDs[0] == input.RunIDs[2] || input.RunIDs[1] == input.RunIDs[2] {
		return PreparedLifecycle{}, fmt.Errorf("%w: lifecycle RunIDs are not distinct", errInvalidAuthority)
	}
	cohort, identityByLabel, err := lifecycleProjection(authority, labels)
	if err != nil || input.RecoveryEndpoint != cohort.CellEndpoint {
		return PreparedLifecycle{}, fmt.Errorf("%w: lifecycle recovery route", errInvalidAuthority)
	}
	authorityRaw, err := CanonicalJSON(authority)
	if err != nil {
		return PreparedLifecycle{}, err
	}
	intent := LifecycleIntent{Schema: lifecycleIntentSchema, ReleaseID: input.ReleaseID, Phase: input.Phase, Attempt: input.Attempt,
		Transport: input.Transport, NHPSourceSHA: authority.NHPSourceSHA, AuthoritySHA256: Digest(authorityRaw), RecoveryEndpoint: input.RecoveryEndpoint,
		Operations: []LifecycleOperationIntent{
			{Role: "primary-first", Label: labels[0], RunID: input.RunIDs[0], RunAttempt: input.Attempt, PreparedAtMS: input.PreparedAt.UTC().UnixMilli(), ExpiresAtMS: input.ExpiresAt.UTC().UnixMilli()},
			{Role: "sibling", Label: labels[1], RunID: input.RunIDs[1], RunAttempt: input.Attempt, PreparedAtMS: input.PreparedAt.UTC().UnixMilli(), ExpiresAtMS: input.ExpiresAt.UTC().UnixMilli()},
			{Role: "primary-replacement", Label: labels[0], RunID: input.RunIDs[2], RunAttempt: input.Attempt, PreparedAtMS: input.PreparedAt.UTC().UnixMilli(), ExpiresAtMS: input.ExpiresAt.UTC().UnixMilli()},
		}}
	intentRaw, err := CanonicalJSON(intent)
	if err != nil {
		return PreparedLifecycle{}, err
	}
	intentKey := fmt.Sprintf("releases/%s/lifecycle-intents/%s/shared/%s/attempt-%d", input.ReleaseID, input.Phase, input.Transport, input.Attempt)
	intentBlob, err := persistImmutable(ctx, c.Blobs, intentKey, "lifecycle-intent", intentRaw)
	if err != nil {
		return PreparedLifecycle{}, fmt.Errorf("persist lifecycle intent before operations: %w", err)
	}
	keys := make([]string, 0, len(intent.Operations))
	for _, operation := range intent.Operations {
		identity := identityByLabel[operation.Label]
		expectedState := identity.AgentState
		if input.AgentStates != nil {
			expectedState = input.AgentStates[operation.Label]
		}
		key, _, prepareErr := c.Prepare(ctx, authority, PrepareOperationRequest{
			ReleaseID: input.ReleaseID, Phase: input.Phase, AWSAccountID: authority.AWSAccountID, AWSRegion: authority.AWSRegion,
			Identity: identity, Cohort: cohort, ExpectedAgentState: expectedState,
			RecoveryEndpoint: input.RecoveryEndpoint, RunID: operation.RunID, RunAttempt: operation.RunAttempt,
			PreparedAt: time.UnixMilli(operation.PreparedAtMS).UTC(), ExpiresAt: time.UnixMilli(operation.ExpiresAtMS).UTC(),
		})
		if prepareErr != nil {
			return PreparedLifecycle{}, fmt.Errorf("prepare lifecycle %s: %w", operation.Role, prepareErr)
		}
		keys = append(keys, key)
	}
	return PreparedLifecycle{IntentReference: blobReference(intentBlob), Intent: intent,
		PrimaryFirstKey: keys[0], SiblingKey: keys[1], ReplacementKey: keys[2]}, nil
}

func lifecycleProjection(authority Authority, labels [2]string) (CohortPlan, map[string]FixedIdentity, error) { //nolint:gocritic // Closed authority values are intentionally copied.
	cohort, err := cohortFor(Plan{Cohorts: authority.Cohorts})
	if err != nil {
		return CohortPlan{}, nil, err
	}
	identities := map[string]FixedIdentity{}
	for index := range authority.Identities {
		identity := authority.Identities[index]
		if identity.Label == labels[0] || identity.Label == labels[1] {
			identities[identity.Label] = identity
		}
	}
	if len(identities) != 2 {
		return CohortPlan{}, nil, fmt.Errorf("%w: lifecycle identity pair", errInvalidAuthority)
	}
	return cohort, identities, nil
}

// ManagedSessionConfig is the real FRP session input for one prepared fixed
// identity. LocalPort is a caller-owned loopback outcome server.
type ManagedSessionConfig struct {
	Consumer             *Consumer
	OperationKey         string
	Identity             FixedIdentity
	LocalIP              string
	LocalPort            int
	ClientVersion        string
	ReplicaDiscriminator string
	Logger               *slog.Logger
	ReadyTimeout         time.Duration
}

// ManagedSession is one admitted FRP tunnel. Stop exact-retires the operation
// and then uses recovery until the durable OP is CLOSED.
type ManagedSession struct {
	consumer *Consumer
	key      string
	sup      *supervisor.Supervisor
	mu       sync.Mutex
	stopped  bool
}

// StartManagedSession connects the real FRP supervisor to the exact durable
// CycleKnocker. It returns only after authenticated Login and proxy readiness.
func StartManagedSession(ctx context.Context, cfg ManagedSessionConfig) (*ManagedSession, error) { //nolint:gocritic // Config is one immutable invocation snapshot.
	if cfg.Consumer == nil || cfg.Consumer.Blobs == nil || !validText(cfg.OperationKey) || cfg.Identity.KnockResourceID == "" ||
		cfg.LocalPort < 1 || cfg.LocalPort > 65535 {
		return nil, fmt.Errorf("%w: managed session input", errInvalidAuthority)
	}
	knocker, err := NewDurableCycleKnocker(ctx, cfg.Consumer, cfg.OperationKey, cfg.Identity.KnockResourceID, cfg.Identity.Selector)
	if err != nil {
		return nil, err
	}
	generated, err := frpgen.Generate(&frpgen.Route{Slug: cfg.Identity.ConnectorID, ResourceID: cfg.Identity.ResourceID,
		ConnectorRoutingID: cfg.Identity.ConnectorRoutingID, LocalIP: cfg.LocalIP, LocalPort: cfg.LocalPort},
		&frpgen.Options{ReplicaDiscriminator: cfg.ReplicaDiscriminator, ClientVersion: cfg.ClientVersion})
	if err != nil {
		return nil, err
	}
	common, proxies := generated.FRPClientConfig()
	if err := common.Complete(); err != nil {
		return nil, fmt.Errorf("complete fixed-canary FRP configuration: %w", err)
	}
	ready := make(chan struct{})
	var readyOnce sync.Once
	factory, err := supervisor.NewFRPRunnerFactory(&supervisor.FRPFactoryConfig{Knocker: knocker,
		ResourceID: cfg.Identity.KnockResourceID, Proxies: proxies, Logger: cfg.Logger,
		OnProxyReady: func() { readyOnce.Do(func() { close(ready) }) }})
	if err != nil {
		return nil, err
	}
	sup, err := supervisor.New(&supervisor.Config{Common: common, Knocker: knocker,
		KnockResourceID: cfg.Identity.KnockResourceID, RunnerFactory: factory, Logger: cfg.Logger})
	if err != nil {
		return nil, err
	}
	if err := sup.Start(ctx); err != nil {
		return nil, err
	}
	timeout := cfg.ReadyTimeout
	if timeout <= 0 || timeout > 30*time.Second {
		timeout = 15 * time.Second
	}
	timer := time.NewTimer(timeout)
	defer timer.Stop()
	select {
	case <-ready:
		return &ManagedSession{consumer: cfg.Consumer, key: cfg.OperationKey, sup: sup}, nil
	case <-sup.Done():
		return nil, errors.Join(fmt.Errorf("fixed-canary session stopped before readiness: %w", sup.Err()),
			settleFailedManagedSession(cfg.Consumer, cfg.OperationKey, sup))
	case <-ctx.Done():
		return nil, errors.Join(ctx.Err(), settleFailedManagedSession(cfg.Consumer, cfg.OperationKey, sup))
	case <-timer.C:
		return nil, errors.Join(errors.New("fixed-canary session readiness timed out"),
			settleFailedManagedSession(cfg.Consumer, cfg.OperationKey, sup))
	}
}

func settleFailedManagedSession(consumer *Consumer, key string, sup *supervisor.Supervisor) error {
	stopCtx, stopCancel := context.WithTimeout(context.Background(), supervisor.StopWait)
	stopErr := sup.Stop(stopCtx)
	stopCancel()
	recoverCtx, recoverCancel := context.WithTimeout(context.Background(), supervisor.StopWait)
	defer recoverCancel()
	terminal, recoverErr := consumer.Recover(recoverCtx, key)
	if recoverErr != nil || (terminal.State != OperationCanceled && terminal.State != OperationClosed) {
		return errors.Join(stopErr, recoverErr, errSessionRecoveryRequired)
	}
	return stopErr
}

// Stop ends the real supervisor and exact-recovers the durable OP to CLOSED.
func (s *ManagedSession) Stop(ctx context.Context) error {
	if s == nil {
		return errors.New("fixed-canary session is nil")
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.stopped {
		terminal, err := s.consumer.Recover(ctx, s.key)
		if err != nil || terminal.State != OperationClosed {
			return errors.Join(err, errSessionRecoveryRequired)
		}
		return nil
	}
	s.stopped = true
	stopErr := s.sup.Stop(ctx)
	recoverCtx, recoverCancel := context.WithTimeout(context.Background(), supervisor.StopWait)
	defer recoverCancel()
	terminal, recoverErr := s.consumer.Recover(recoverCtx, s.key)
	if recoverErr != nil || terminal.State != OperationClosed {
		return errors.Join(stopErr, recoverErr, errSessionRecoveryRequired)
	}
	return stopErr
}

// LifecycleOutcome is the exact customer journey result. The caller owns GET
// checks and sibling-continuity observation around these real sessions.
type LifecycleOutcome struct {
	Transport                  string `json:"transport"`
	PrimaryFirstRunID          string `json:"primary_first_run_id"`
	SiblingRunID               string `json:"sibling_run_id"`
	PrimaryReplacementRunID    string `json:"primary_replacement_run_id"`
	PrimaryExactRetirement     bool   `json:"primary_exact_retirement"`
	GetBothBeforeRetire        bool   `json:"get_both_before_retire"`
	SiblingContinued           bool   `json:"sibling_continued"`
	ReplacementReady           bool   `json:"replacement_ready"`
	GetBothAfterReplacement    bool   `json:"get_both_after_replacement"`
	ReplacementExactRetirement bool   `json:"replacement_exact_retirement"`
	SiblingExactRetirement     bool   `json:"sibling_exact_retirement"`
}

// LifecycleSettlement is the recovery-only result for an attempt that crossed
// a network boundary before it could persist a completed customer outcome.
// The attempt is never replayed. A durable orchestration journal may create
// attempt+1 only after every old operation is CANCELED or CLOSED.
type LifecycleSettlement struct {
	Attempt        uint64   `json:"attempt"`
	OperationKeys  []string `json:"operation_keys"`
	TerminalStates []string `json:"terminal_states"`
	RetryRequired  bool     `json:"retry_required"`
}

// LifecycleSession is one running fixed-identity Connector. Alive is a
// nonblocking check. Stop must not return success until the durable operation
// is exact CLOSED.
type LifecycleSession interface {
	Alive() error
	Stop(context.Context) error
}

// LifecycleSessionLauncher starts one already-prepared operation. It may not
// create a RunID or emit a KNK outside the supplied key.
type LifecycleSessionLauncher interface {
	Start(context.Context, string, FixedIdentity) (LifecycleSession, error)
}

// LifecycleProbe performs the real customer GET outcomes.
type LifecycleProbe interface {
	Both(context.Context, FixedIdentity, FixedIdentity) error
	Sibling(context.Context, FixedIdentity) error
}

// ManagedSessionLauncher connects prepared operations to the real FRP
// supervisor. Targets are exact caller-owned local host:port values keyed by
// the two selected identity labels.
type ManagedSessionLauncher struct {
	Consumer      *Consumer
	Targets       map[string]string
	ClientVersion string
	Logger        *slog.Logger
	ReadyTimeout  time.Duration
}

// Start implements LifecycleSessionLauncher.
func (l *ManagedSessionLauncher) Start(ctx context.Context, key string, identity FixedIdentity) (LifecycleSession, error) { //nolint:gocritic // Identity is one immutable authority row.
	if l == nil || l.Consumer == nil || len(l.Targets) != 2 {
		return nil, fmt.Errorf("%w: lifecycle session launcher", errInvalidAuthority)
	}
	target, ok := l.Targets[identity.Label]
	if !ok {
		return nil, fmt.Errorf("%w: lifecycle local target", errInvalidAuthority)
	}
	host, port, err := supervisor.ParseResourceHost(target)
	if err != nil {
		return nil, fmt.Errorf("parse lifecycle local target: %w", err)
	}
	return StartManagedSession(ctx, ManagedSessionConfig{Consumer: l.Consumer, OperationKey: key, Identity: identity,
		LocalIP: host, LocalPort: port, ClientVersion: l.ClientVersion,
		ReplicaDiscriminator: "fixed-shared-" + identity.Label,
		Logger:               l.Logger, ReadyTimeout: l.ReadyTimeout})
}

// Alive reports an autonomous supervisor exit without blocking.
func (s *ManagedSession) Alive() error {
	if s == nil || s.sup == nil {
		return errors.New("fixed-canary session is nil")
	}
	select {
	case <-s.sup.Done():
		return fmt.Errorf("fixed-canary session stopped: %w", s.sup.Err())
	default:
		return nil
	}
}

// RunPreparedLifecycle executes the complete primary/sibling/replacement
// journey. It starts no process until the immutable intent and all three
// operation rows pass fresh durable readback. Partial starts are exact-settled.
//
//nolint:gocritic // The immutable snapshots are part of the customer outcome contract.
func (c *Consumer) RunPreparedLifecycle(ctx context.Context, authority Authority, prepared PreparedLifecycle,
	launcher LifecycleSessionLauncher, probe LifecycleProbe,
) (LifecycleOutcome, error) {
	authorityRaw, encodeErr := CanonicalJSON(authority)
	if launcher == nil || probe == nil || ValidateAuthority(authority) != nil || encodeErr != nil ||
		Digest(authorityRaw) != prepared.Intent.AuthoritySHA256 {
		return LifecycleOutcome{}, fmt.Errorf("%w: lifecycle execution authority", errInvalidAuthority)
	}
	if err := c.ValidatePreparedLifecycle(ctx, prepared); err != nil {
		return LifecycleOutcome{}, err
	}
	labels, ok := lifecycleLabels[prepared.Intent.Transport]
	if !ok {
		return LifecycleOutcome{}, fmt.Errorf("%w: lifecycle transport", errInvalidAuthority)
	}
	_, identities, err := lifecycleProjection(authority, labels)
	if err != nil {
		return LifecycleOutcome{}, err
	}
	primary, sibling := identities[labels[0]], identities[labels[1]]
	primarySession, siblingSession, err := startLifecyclePair(ctx, launcher,
		prepared.PrimaryFirstKey, primary, prepared.SiblingKey, sibling)
	if err != nil {
		return LifecycleOutcome{}, err
	}
	if err := probe.Both(ctx, primary, sibling); err != nil {
		return LifecycleOutcome{}, errors.Join(err, stopLifecycleSession(primarySession), stopLifecycleSession(siblingSession))
	}
	if err := stopLifecycleSession(primarySession); err != nil {
		return LifecycleOutcome{}, errors.Join(err, stopLifecycleSession(siblingSession))
	}
	if err := siblingSession.Alive(); err != nil {
		return LifecycleOutcome{}, errors.Join(err, stopLifecycleSession(siblingSession))
	}
	if err := probe.Sibling(ctx, sibling); err != nil {
		return LifecycleOutcome{}, errors.Join(err, stopLifecycleSession(siblingSession))
	}
	replacement, err := launcher.Start(ctx, prepared.ReplacementKey, primary)
	if err != nil {
		return LifecycleOutcome{}, errors.Join(err, stopLifecycleSession(siblingSession))
	}
	if err := siblingSession.Alive(); err != nil {
		return LifecycleOutcome{}, errors.Join(err, stopLifecycleSession(replacement), stopLifecycleSession(siblingSession))
	}
	if err := probe.Both(ctx, primary, sibling); err != nil {
		return LifecycleOutcome{}, errors.Join(err, stopLifecycleSession(replacement), stopLifecycleSession(siblingSession))
	}
	replacementErr, siblingErr := stopLifecyclePair(replacement, siblingSession)
	if replacementErr != nil || siblingErr != nil {
		return LifecycleOutcome{}, errors.Join(replacementErr, siblingErr)
	}
	return LifecycleOutcome{Transport: prepared.Intent.Transport,
		PrimaryFirstRunID:       prepared.Intent.Operations[0].RunID,
		SiblingRunID:            prepared.Intent.Operations[1].RunID,
		PrimaryReplacementRunID: prepared.Intent.Operations[2].RunID,
		PrimaryExactRetirement:  true, GetBothBeforeRetire: true, SiblingContinued: true,
		ReplacementReady: true, GetBothAfterReplacement: true,
		ReplacementExactRetirement: true, SiblingExactRetirement: true}, nil
}

type lifecycleStartResult struct {
	index   int
	session LifecycleSession
	err     error
}

//nolint:gocritic // Fixed identities are immutable authority rows copied into two concurrent starts.
func startLifecyclePair(ctx context.Context, launcher LifecycleSessionLauncher, firstKey string, first FixedIdentity,
	secondKey string, second FixedIdentity,
) (firstSession LifecycleSession, secondSession LifecycleSession, startErr error) {
	startCtx, cancel := context.WithCancel(ctx)
	defer cancel()
	results := make(chan lifecycleStartResult, 2)
	inputs := []struct {
		key      string
		identity FixedIdentity
	}{{firstKey, first}, {secondKey, second}}
	for index := range inputs {
		input := &inputs[index]
		go func(index int, key string, identity FixedIdentity) {
			session, err := launcher.Start(startCtx, key, identity)
			results <- lifecycleStartResult{index: index, session: session, err: err}
		}(index, input.key, input.identity)
	}
	values := [2]lifecycleStartResult{}
	var errs []error
	for range 2 {
		value := <-results
		values[value.index] = value
		if value.err != nil {
			errs = append(errs, value.err)
			cancel()
		}
	}
	if len(errs) > 0 {
		for _, value := range values {
			if value.session != nil {
				errs = append(errs, stopLifecycleSession(value.session))
			}
		}
		return nil, nil, errors.Join(errs...)
	}
	return values[0].session, values[1].session, nil
}

func stopLifecyclePair(first, second LifecycleSession) (firstErr, secondErr error) {
	results := make(chan struct {
		index int
		err   error
	}, 2)
	go func() {
		results <- struct {
			index int
			err   error
		}{0, stopLifecycleSession(first)}
	}()
	go func() {
		results <- struct {
			index int
			err   error
		}{1, stopLifecycleSession(second)}
	}()
	values := [2]error{}
	for range 2 {
		value := <-results
		values[value.index] = value.err
	}
	return values[0], values[1]
}

func stopLifecycleSession(session LifecycleSession) error {
	ctx, cancel := context.WithTimeout(context.Background(), supervisor.StopWait)
	defer cancel()
	return session.Stop(ctx)
}

// ValidatePreparedLifecycle ensures a restored receipt and its operation rows
// still form the exact immutable pre-network bundle.
//
//nolint:gocritic // PreparedLifecycle is one immutable authority snapshot.
func (c *Consumer) ValidatePreparedLifecycle(ctx context.Context, prepared PreparedLifecycle) error {
	_, err := c.validateLifecycleBundle(ctx, prepared, true)
	return err
}

//nolint:gocritic,gocyclo // PreparedLifecycle is one immutable authority snapshot with a closed cross-binding union.
func (c *Consumer) validateLifecycleBundle(ctx context.Context, prepared PreparedLifecycle, requirePrepared bool) ([]OperationRecord, error) {
	if c == nil || c.Blobs == nil || !validLifecycleIntent(prepared.Intent) {
		return nil, fmt.Errorf("%w: prepared lifecycle", errInvalidAuthority)
	}
	raw, err := CanonicalJSON(prepared.Intent)
	if err != nil {
		return nil, err
	}
	blob, err := c.Blobs.Load(ctx, prepared.IntentReference.Key)
	expectedIntentKey := fmt.Sprintf("releases/%s/lifecycle-intents/%s/shared/%s/attempt-%d", prepared.Intent.ReleaseID,
		prepared.Intent.Phase, prepared.Intent.Transport, prepared.Intent.Attempt)
	if err != nil || prepared.IntentReference.Key != expectedIntentKey || blobReference(blob) != prepared.IntentReference || !bytes.Equal(blob.Body, raw) {
		return nil, fmt.Errorf("%w: lifecycle intent readback", errStateConflict)
	}
	records := make([]OperationRecord, 0, 3)
	for index, key := range []string{prepared.PrimaryFirstKey, prepared.SiblingKey, prepared.ReplacementKey} {
		record, _, loadErr := loadOperation(ctx, c.Blobs, key)
		want := prepared.Intent.Operations[index]
		if loadErr != nil || record.ReleaseID != prepared.Intent.ReleaseID || record.Phase != prepared.Intent.Phase ||
			record.NHPSourceSHA != prepared.Intent.NHPSourceSHA || record.AuthoritySHA256 != prepared.Intent.AuthoritySHA256 ||
			record.RecoveryEndpoint != prepared.Intent.RecoveryEndpoint || record.Operation.RunID != want.RunID ||
			record.Operation.RunAttempt != want.RunAttempt || record.Operation.PreparedAtMillis != want.PreparedAtMS ||
			record.Operation.ExpiresAtMillis != want.ExpiresAtMS || record.Label != want.Label ||
			record.Operation.ResourceID == "" {
			return nil, fmt.Errorf("%w: lifecycle operation %s", errStateConflict, want.Role)
		}
		if requirePrepared && record.Status != OperationPrepared {
			return nil, fmt.Errorf("%w: lifecycle operation %s already dispatched", errStateConflict, want.Role)
		}
		records = append(records, record)
	}
	return records, nil
}

func validLifecycleIntent(intent LifecycleIntent) bool { //nolint:gocritic,gocyclo // Intent is one immutable closed authority snapshot.
	labels, ok := lifecycleLabels[intent.Transport]
	if !ok || intent.Schema != lifecycleIntentSchema || !hex64Pattern.MatchString(intent.ReleaseID) || !hex40Pattern.MatchString(intent.NHPSourceSHA) ||
		intent.Phase != "fixed_shared_"+intent.Transport || intent.Attempt == 0 || !hex64Pattern.MatchString(intent.AuthoritySHA256) ||
		intent.RecoveryEndpoint.Port != 443 || !validDNS(intent.RecoveryEndpoint.Host) ||
		!validBase64Raw32(intent.RecoveryEndpoint.ServerPublicKeyB64) || len(intent.Operations) != 3 {
		return false
	}
	wantRoles := [3]string{"primary-first", "sibling", "primary-replacement"}
	wantLabels := [3]string{labels[0], labels[1], labels[0]}
	seenRunIDs := make(map[string]struct{}, len(intent.Operations))
	var preparedAt, expiresAt int64
	for index := range intent.Operations {
		operation := intent.Operations[index]
		if operation.Role != wantRoles[index] || operation.Label != wantLabels[index] || operation.RunAttempt != intent.Attempt ||
			qurl.ValidateCycleRunID(operation.RunID) != nil || operation.PreparedAtMS <= 0 || operation.ExpiresAtMS <= operation.PreparedAtMS ||
			operation.ExpiresAtMS-operation.PreparedAtMS > int64(30*time.Minute/time.Millisecond) {
			return false
		}
		if index == 0 {
			preparedAt, expiresAt = operation.PreparedAtMS, operation.ExpiresAtMS
		} else if operation.PreparedAtMS != preparedAt || operation.ExpiresAtMS != expiresAt {
			return false
		}
		if _, duplicate := seenRunIDs[operation.RunID]; duplicate {
			return false
		}
		seenRunIDs[operation.RunID] = struct{}{}
	}
	return true
}

// LifecycleAttemptNeedsSettlement returns true only for an exact immutable
// bundle where one or more operations have crossed the durable dispatch
// boundary. Corrupt or mismatched bundles fail instead of authorizing retry.
//
//nolint:gocritic // PreparedLifecycle is one immutable authority snapshot.
func (c *Consumer) LifecycleAttemptNeedsSettlement(ctx context.Context, prepared PreparedLifecycle) (bool, error) {
	records, err := c.validateLifecycleBundle(ctx, prepared, false)
	if err != nil {
		return false, err
	}
	for index := range records {
		record := records[index]
		if record.Status != OperationPrepared {
			return true, nil
		}
	}
	return false, nil
}

// SettlePreparedLifecycle recovers every old operation without admitting a
// replacement. It accepts CANCELED or CLOSED as terminal. CLOSING, missing, or
// malformed authority keeps this attempt active and blocks attempt+1.
func (c *Consumer) SettlePreparedLifecycle(ctx context.Context, authority Authority, prepared PreparedLifecycle, recoveryBudget time.Duration) (LifecycleSettlement, error) { //nolint:gocritic // One exact immutable bundle is recovered as a set.
	authorityRaw, encodeErr := CanonicalJSON(authority)
	if ValidateAuthority(authority) != nil || encodeErr != nil || Digest(authorityRaw) != prepared.Intent.AuthoritySHA256 ||
		recoveryBudget <= 0 || recoveryBudget > 30*time.Second {
		return LifecycleSettlement{}, fmt.Errorf("%w: lifecycle settlement authority", errInvalidAuthority)
	}
	if _, err := c.validateLifecycleBundle(ctx, prepared, false); err != nil {
		return LifecycleSettlement{}, err
	}
	keys := []string{prepared.PrimaryFirstKey, prepared.SiblingKey, prepared.ReplacementKey}
	type terminalResult struct {
		index    int
		terminal SessionTerminal
		err      error
	}
	results := make(chan terminalResult, len(keys))
	for index, key := range keys {
		go func(index int, key string) { //nolint:gosec // Exact recovery must outlive caller cancellation and has a strict bound.
			recoveryCtx, cancel := context.WithTimeout(context.Background(), recoveryBudget)
			defer cancel()
			terminal, err := c.Recover(recoveryCtx, key)
			results <- terminalResult{index: index, terminal: terminal, err: err}
		}(index, key)
	}
	ordered := make([]terminalResult, len(keys))
	for range keys {
		result := <-results
		ordered[result.index] = result
	}
	settlement := LifecycleSettlement{Attempt: prepared.Intent.Attempt, OperationKeys: append([]string(nil), keys...),
		TerminalStates: make([]string, 0, len(keys)), RetryRequired: true}
	var failures []error
	for index, result := range ordered {
		if result.err != nil || (result.terminal.State != OperationCanceled && result.terminal.State != OperationClosed) {
			failures = append(failures, fmt.Errorf("settle lifecycle operation %d: %w", index,
				errors.Join(result.err, terminalError(result.terminal))))
			continue
		}
		settlement.TerminalStates = append(settlement.TerminalStates, result.terminal.State)
	}
	if len(failures) != 0 {
		return LifecycleSettlement{}, errors.Join(failures...)
	}
	return settlement, nil
}
