name: Terraform Validate

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [sandbox, prod]
    defaults:
      run:
        working-directory: terraform/environments/${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.14"

      - name: Terraform fmt
        run: terraform fmt -check -recursive ../../
        working-directory: terraform

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate
